import type { Project } from '@8f4e/editor-state-types';

const ericSaiteGenerator: Project = {
	codeBlocks: [
		{
			code: [
				'config',
				'; @pos -241 -15',
				'; @config runtime WebWorkerMIDIRuntime',
				'; ~sampleRate 50',
				'',
				'',
				'configEnd',
			],
		},
		{
			code: [
				'module bufferToOut',
				'; @pos -96 -2',
				'',
				'float* bufferIn &notesMux2:out.notes',
				'float out1',
				'float out2',
				'float out3',
				'float out4',
				'',
				'push &out1',
				'push bufferIn',
				'load',
				'loadFloat',
				'store',
				'',
				'push &out2',
				'push bufferIn',
				'load',
				'push %bufferIn',
				'add',
				'loadFloat',
				'store',
				'',
				'push &out3',
				'push bufferIn',
				'load',
				'push %bufferIn',
				'push 2',
				'mul',
				'add',
				'loadFloat',
				'store',
				'',
				'push &out4',
				'push bufferIn',
				'load',
				'push %bufferIn',
				'push 3',
				'mul',
				'add',
				'loadFloat',
				'store',
				'',
				'moduleEnd',
			],
		},
		{
			code: [
				'module chord2',
				'; @pos -187 -2',
				'float[] notes 12 59.0 62.0 66.0',
				'int length 3',
				'; @piano notes length 48',
				'moduleEnd',
			],
		},
		{
			code: [
				'module chord3',
				'; @pos -187 13',
				'float[] notes 12 66.0 57.0 61.0',
				'int length 3',
				'; @piano notes length 48',
				'moduleEnd',
			],
		},
		{
			code: [
				'module chord4',
				'; @pos -238 -2',
				'float[] notes 12 43.0 -1.0 -1.0',
				'int length 1',
				'; @piano notes length 36',
				'moduleEnd',
			],
		},
		{
			code: [
				'module chord5',
				'; @pos -238 13',
				'float[] notes 12 38.0 -1.0 -1.0',
				'int length 2',
				'; @piano notes length 36',
				'moduleEnd',
			],
		},
		{
			code: [
				'module clock',
				'; @pos -175 -23',
				'',
				'const HIGH 1',
				'const LOW 0',
				'',
				'int out',
				'',
				'push &out',
				'push out',
				'push HIGH',
				'equal',
				'if',
				'push LOW',
				'else',
				'push HIGH',
				'ifEnd int',
				'store',
				'',
				'moduleEnd',
			],
		},
		{
			code: [
				'module clockDivider',
				'; @pos -140 -46',
				'',
				'int default 48',
				'int* divider &default',
				'int* trigger &clock:out',
				'int out',
				'int counter',
				'',
				'; @watch out',
				'',
				'; Avoid remainder by zero',
				'push *divider',
				'push 0',
				'equal',
				'branchIfTrue 0',
				'',
				'push *trigger',
				'risingEdge',
				'if',
				'push &counter',
				'push counter',
				'push 1',
				'add',
				'store ',
				'ifEnd',
				'',
				'push counter',
				'push *divider',
				'ensureNonZero',
				'remainder',
				'push 0',
				'equal',
				'if',
				'push &out',
				'push *trigger',
				'store',
				'else',
				'push &out',
				'push 0',
				'store',
				'ifEnd',
				'',
				'moduleEnd',
			],
		},
		{
			code: [
				'module clockDivider2',
				'; @pos -105 -46',
				'',
				'int default 24',
				'int* divider &default',
				'int* trigger &clock:out',
				'int out',
				'int counter',
				'',
				'; @watch out',
				'',
				'; Avoid remainder by zero',
				'push *divider',
				'push 0',
				'equal',
				'branchIfTrue 0',
				'',
				'push *trigger',
				'risingEdge',
				'if',
				'push &counter',
				'push counter',
				'push 1',
				'add',
				'store ',
				'ifEnd',
				'',
				'push counter',
				'push *divider',
				'ensureNonZero',
				'remainder',
				'push 0',
				'equal',
				'if',
				'push &out',
				'push *trigger',
				'store',
				'else',
				'push &out',
				'push 0',
				'store',
				'ifEnd',
				'',
				'moduleEnd',
			],
		},
		{
			code: [
				'module lcg',
				'; @pos -187 53',
				'; Linear congruential ',
				'; generator',
				'',
				'const MULTIPLIER 1664525',
				'const INCREMENT 1013904223 ',
				'const MODULUS 65536 ; 2^16',
				'int seed 69420',
				'',
				'float out',
				'',
				'push &seed',
				'push MULTIPLIER',
				'push seed',
				'mul',
				'push INCREMENT',
				'add',
				'push MODULUS',
				'ensureNonZero',
				'remainder',
				'store',
				'',
				'push &out',
				'push seed',
				'castToFloat',
				'push MODULUS',
				'castToFloat',
				'ensureNonZero',
				'div ',
				'store',
				'',
				'moduleEnd',
			],
		},
		{
			code: [
				'module mapToRange2',
				'; @pos -150 53',
				'',
				'const IN_RANGE_MIN -1.0',
				'const IN_RANGE_MAX 1.0',
				'',
				'float* in &lcg:out',
				'float outRangeMin 69.0',
				'float outRangeMax 81.0',
				'float out',
				'',
				'; @watch out',
				'',
				'push &out',
				'push *in',
				'push IN_RANGE_MIN',
				'sub',
				'push IN_RANGE_MAX',
				'push IN_RANGE_MIN',
				'sub',
				'ensureNonZero',
				'div',
				'push outRangeMax',
				'push outRangeMin',
				'sub',
				'mul',
				'push outRangeMin',
				'add',
				'store',
				'',
				'moduleEnd',
			],
		},
		{
			code: [
				'module midinoteout',
				'; @pos -50 38',
				'',
				'float* noteIn &quantizer:out',
				'int channel 1',
				'int* gate &clockDivider2:out',
				'int velocity 100',
				'int note ',
				'',
				'push &note',
				'push *noteIn',
				'castToInt',
				'store',
				'',
				'moduleEnd',
			],
		},
		{
			code: [
				'module midinoteout2',
				'; @pos -50 -10',
				'',
				'float* noteIn &bufferToOut:out1',
				'int channel 1',
				'int* gate &clockDivider:out',
				'int velocity 127',
				'int note ',
				'',
				'push &note',
				'push *noteIn',
				'castToInt',
				'store',
				'',
				'moduleEnd',
			],
		},
		{
			code: [
				'module midinoteout3',
				'; @pos -50 6',
				'',
				'float* noteIn &bufferToOut:out2',
				'int channel 1',
				'int* gate &clockDivider:out',
				'int velocity 127',
				'int note ',
				'',
				'push &note',
				'push *noteIn',
				'castToInt',
				'store',
				'',
				'moduleEnd',
			],
		},
		{
			code: [
				'module midinoteout4',
				'; @pos -50 22',
				'',
				'float* noteIn &bufferToOut:out3',
				'int channel 1',
				'int* gate &clockDivider:out',
				'int velocity 127',
				'int note ',
				'',
				'push &note',
				'push *noteIn',
				'castToInt',
				'store',
				'',
				'moduleEnd',
			],
		},
		{
			code: [
				'module notesMux2',
				'; @pos -136 -2',
				'',
				'int* in0 &chord4:notes',
				'int* in1 &chord2:notes',
				'int* in2 &chord5:notes',
				'int* in3 &chord3:notes',
				'int* in4',
				'int* in5',
				'int* in6',
				'int* in7',
				'',
				'int _length 4; default',
				'int* trigger &clockDivider:out',
				'int* length &_length',
				'',
				'int out',
				'',
				'int counter',
				'',
				'push *trigger',
				'risingEdge',
				'if',
				' ; Increment counter',
				'push &counter',
				'push counter',
				'push 1',
				'add',
				'store',
				'ifEnd',
				'',
				'; Guard',
				'push counter',
				'push *length',
				'greaterOrEqual',
				'if',
				'push &counter',
				'push 0',
				'store',
				'ifEnd',
				'',
				'push &out',
				' ; Calculate input address',
				'push &in0',
				'push counter',
				'push %in0',
				'mul',
				'add',
				'',
				' ; Load value',
				'load',
				'store',
				'',
				'moduleEnd',
			],
		},
		{
			code: [
				'module quantizer',
				'; @pos -115 53',
				'',
				'float* in &mapToRange2:out',
				'float* buffer &scale1:notes',
				'int* length &scale1:length',
				'float out',
				'',
				'; @watch out',
				'',
				'float* _levelPointer',
				'float _difference',
				'float _smallestDiff 1000',
				'',
				'; @watch &_smallestDiff',
				'',
				'push &_smallestDiff',
				'push 1000.0',
				'store',
				'',
				'push &_levelPointer',
				'push buffer',
				'store',
				'',
				'loop',
				' ; Calculate difference ',
				' ; between the input and',
				' ; the current level.',
				'push &_difference',
				'push *_levelPointer',
				'push *in',
				'sub',
				'abs',
				'store',
				'',
				'push _difference',
				'push _smallestDiff',
				'lessOrEqual',
				'if',
				"  ; If it's actually smaller",
				'  ; than the smallest difference,',
				'  ; then update the smallest ',
				'  ; difference.',
				'push &_smallestDiff',
				'push _difference',
				'store',
				'  ; Save the current level value.',
				'push &out',
				'push *_levelPointer',
				'store',
				'ifEnd',
				'',
				' ; Guard',
				'push _levelPointer',
				'push buffer',
				'push *length',
				'push 1',
				'sub',
				'push %buffer',
				'mul',
				'add',
				'greaterOrEqual',
				'branchIfTrue 1 ',
				'',
				' ; Increment level pointer',
				'push &_levelPointer',
				'push _levelPointer',
				'push %buffer',
				'add',
				'store',
				'loopEnd',
				'',
				'moduleEnd',
			],
		},
		{
			code: [
				'module scale1',
				'; @pos -187 28',
				'float[] notes 12 78.0 79.0 73.0 74.0 71.0 69.0 81.0',
				'int length 7',
				'; @piano notes length 60',
				'moduleEnd',
			],
		},
	],
};

export default ericSaiteGenerator;
