import type { Project } from '@8f4e/editor-state';

const ericSaiteGenerator: Project = {
	codeBlocks: [
		{
			code: [
				'config',
				'; @pos -241 -15',
				'',
				'scope "memorySizeBytes"',
				'push 65536',
				'set',
				'popScope',
				'',
				'scope "runtimeSettings"',
				'scope "runtime"',
				'push "WebWorkerMIDIRuntime"',
				'set',
				'rescopeTop "sampleRate"',
				'push 50',
				'set',
				'popScope',
				'',
				'configEnd',
			],
		},
		{
			code: [
				'module bufferToOut',
				'; @pos -96 -2',
				'',
				'float* bufferIn &notesMux2.out.notes',
				'float out1',
				'float out2',
				'float out3',
				'float out4',
				'',
				'push &out1',
				'push bufferIn',
				'load',
				'loadFloat',
				'store',
				'',
				'push &out2',
				'push bufferIn',
				'load',
				'push %bufferIn',
				'add',
				'loadFloat',
				'store',
				'',
				'push &out3',
				'push bufferIn',
				'load',
				'push %bufferIn',
				'push 2',
				'mul',
				'add',
				'loadFloat',
				'store',
				'',
				'push &out4',
				'push bufferIn',
				'load',
				'push %bufferIn',
				'push 3',
				'mul',
				'add',
				'loadFloat',
				'store',
				'',
				'moduleEnd',
			],
		},
		{
			code: [
				'module chord2',
				'; @pos -187 -2',
				'float[] notes 12',
				'int length 3',
				'; @piano notes length 48',
				'init notes[0] 59.0',
				'init notes[1] 62.0',
				'init notes[2] 66.0',
				'moduleEnd',
			],
		},
		{
			code: [
				'module chord3',
				'; @pos -187 13',
				'float[] notes 12',
				'int length 3',
				'; @piano notes length 48',
				'init notes[0] 66.0',
				'init notes[1] 57.0',
				'init notes[2] 61.0',
				'moduleEnd',
			],
		},
		{
			code: [
				'module chord4',
				'; @pos -238 -2',
				'float[] notes 12',
				'int length 1',
				'; @piano notes length 36',
				'init notes[1] -1.0',
				'init notes[2] -1.0',
				'init notes[0] 43.0',
				'moduleEnd',
			],
		},
		{
			code: [
				'module chord5',
				'; @pos -238 13',
				'float[] notes 12',
				'int length 2',
				'; @piano notes length 36',
				'init notes[0] 38.0',
				'init notes[1] -1.0',
				'init notes[2] -1.0',
				'moduleEnd',
			],
		},
		{
			code: [
				'module clock',
				'; @pos -175 -23',
				'',
				'const HIGH 1',
				'const LOW 0',
				'',
				'int out',
				'',
				'push &out',
				'push out',
				'push HIGH',
				'equal',
				'if int',
				' push LOW',
				'else',
				' push HIGH',
				'ifEnd',
				'store',
				'',
				'moduleEnd',
			],
		},
		{
			code: [
				'module clockDivider',
				'; @pos -140 -46',
				'',
				'int default 48',
				'int* divider &default',
				'int* trigger &clock.out',
				'int out',
				'int counter',
				'',
				'; @debug out',
				'',
				'; Avoid remainder by zero',
				'push *divider',
				'push 0',
				'equal',
				'branchIfTrue 0',
				'',
				'push *trigger',
				'risingEdge',
				'if void',
				' push &counter',
				' push counter',
				' push 1',
				' add',
				' store ',
				'ifEnd',
				'',
				'push counter',
				'push *divider',
				'ensureNonZero',
				'remainder',
				'push 0',
				'equal',
				'if void',
				' push &out',
				' push *trigger',
				' store',
				'else',
				' push &out',
				' push 0',
				' store',
				'ifEnd',
				'',
				'moduleEnd',
			],
		},
		{
			code: [
				'module clockDivider2',
				'; @pos -105 -46',
				'',
				'int default 24',
				'int* divider &default',
				'int* trigger &clock.out',
				'int out',
				'int counter',
				'',
				'; @debug out',
				'',
				'; Avoid remainder by zero',
				'push *divider',
				'push 0',
				'equal',
				'branchIfTrue 0',
				'',
				'push *trigger',
				'risingEdge',
				'if void',
				' push &counter',
				' push counter',
				' push 1',
				' add',
				' store ',
				'ifEnd',
				'',
				'push counter',
				'push *divider',
				'ensureNonZero',
				'remainder',
				'push 0',
				'equal',
				'if void',
				' push &out',
				' push *trigger',
				' store',
				'else',
				' push &out',
				' push 0',
				' store',
				'ifEnd',
				'',
				'moduleEnd',
			],
		},
		{
			code: [
				'module lcg',
				'; @pos -187 53',
				'; Linear congruential ',
				'; generator',
				'',
				'const MULTIPLIER 1664525',
				'const INCREMENT 1013904223 ',
				'const MODULUS 65536 ; 2^16',
				'int seed 69420',
				'',
				'float out',
				'',
				'push &seed',
				' push MULTIPLIER',
				' push seed',
				' mul',
				' push INCREMENT',
				' add',
				' push MODULUS',
				' ensureNonZero',
				' remainder',
				'store',
				'',
				'push &out',
				' push seed',
				' castToFloat',
				' push MODULUS',
				' castToFloat',
				' ensureNonZero',
				' div ',
				'store',
				'',
				'moduleEnd',
			],
		},
		{
			code: [
				'module mapToRange2',
				'; @pos -150 53',
				'',
				'const IN_RANGE_MIN -1.0',
				'const IN_RANGE_MAX 1.0',
				'',
				'float* in &lcg.out',
				'float outRangeMin 69.0',
				'float outRangeMax 81.0',
				'float out',
				'',
				'; @debug out',
				'',
				'push &out',
				'push *in',
				'push IN_RANGE_MIN',
				'sub',
				'push IN_RANGE_MAX',
				'push IN_RANGE_MIN',
				'sub',
				'ensureNonZero',
				'div',
				'push outRangeMax',
				'push outRangeMin',
				'sub',
				'mul',
				'push outRangeMin',
				'add',
				'store',
				'',
				'moduleEnd',
			],
		},
		{
			code: [
				'module midinoteout',
				'; @pos -50 38',
				'',
				'float* noteIn &quantizer.out',
				'int channel 1',
				'int* gate &clockDivider2.out',
				'int velocity 100',
				'int note ',
				'',
				'push &note',
				'push *noteIn',
				'castToInt',
				'store',
				'',
				'moduleEnd',
			],
		},
		{
			code: [
				'module midinoteout2',
				'; @pos -50 -10',
				'',
				'float* noteIn &bufferToOut.out1',
				'int channel 1',
				'int* gate &clockDivider.out',
				'int velocity 127',
				'int note ',
				'',
				'push &note',
				'push *noteIn',
				'castToInt',
				'store',
				'',
				'moduleEnd',
			],
		},
		{
			code: [
				'module midinoteout3',
				'; @pos -50 6',
				'',
				'float* noteIn &bufferToOut.out2',
				'int channel 1',
				'int* gate &clockDivider.out',
				'int velocity 127',
				'int note ',
				'',
				'push &note',
				'push *noteIn',
				'castToInt',
				'store',
				'',
				'moduleEnd',
			],
		},
		{
			code: [
				'module midinoteout4',
				'; @pos -50 22',
				'',
				'float* noteIn &bufferToOut.out3',
				'int channel 1',
				'int* gate &clockDivider.out',
				'int velocity 127',
				'int note ',
				'',
				'push &note',
				'push *noteIn',
				'castToInt',
				'store',
				'',
				'moduleEnd',
			],
		},
		{
			code: [
				'module notesMux2',
				'; @pos -136 -2',
				'',
				'int* in0 &chord4.notes',
				'int* in1 &chord2.notes',
				'int* in2 &chord5.notes',
				'int* in3 &chord3.notes',
				'int* in4',
				'int* in5',
				'int* in6',
				'int* in7',
				'',
				'int _length 4; default',
				'int* trigger &clockDivider.out',
				'int* length &_length',
				'',
				'int out',
				'',
				'int counter',
				'',
				'push *trigger',
				'risingEdge',
				'if void ',
				' ; Increment counter',
				' push &counter',
				'  push counter',
				'  push 1',
				'  add',
				' store',
				'ifEnd',
				'',
				'; Guard',
				'push counter',
				'push *length',
				'greaterOrEqual',
				'if void',
				' push &counter',
				'  push 0',
				' store',
				'ifEnd',
				'',
				'push &out',
				' ; Calculate input address',
				' push &in0',
				' push counter',
				' push %in0',
				' mul',
				' add',
				'',
				' ; Load value',
				' load',
				'store',
				'',
				'moduleEnd',
			],
		},
		{
			code: [
				'module quantizer',
				'; @pos -115 53',
				'',
				'float* in &mapToRange2.out',
				'float* buffer &scale1.notes',
				'int* length &scale1.length',
				'float out',
				'',
				'; @debug out',
				'',
				'float* _levelPointer',
				'float _difference',
				'float _smallestDiff 1000',
				'',
				'; @debug &_smallestDiff',
				'',
				'push &_smallestDiff',
				'push 1000.0',
				'store',
				'',
				'push &_levelPointer',
				'push buffer',
				'store',
				'',
				'loop',
				' ; Calculate difference ',
				' ; between the input and',
				' ; the current level.',
				' push &_difference',
				' push *_levelPointer',
				' push *in',
				' sub',
				' abs',
				' store',
				'',
				' push _difference',
				' push _smallestDiff',
				' lessOrEqual',
				' if void',
				"  ; If it's actually smaller",
				'  ; than the smallest difference,',
				'  ; then update the smallest ',
				'  ; difference.',
				'  push &_smallestDiff',
				'  push _difference',
				'  store',
				'  ; Save the current level value.',
				'  push &out',
				'  push *_levelPointer',
				'  store',
				' ifEnd',
				'',
				' ; Guard',
				' push _levelPointer',
				' push buffer',
				' push *length',
				' push 1',
				' sub',
				' push %buffer',
				' mul',
				' add',
				' greaterOrEqual',
				' branchIfTrue 1 ',
				'',
				' ; Increment level pointer',
				' push &_levelPointer',
				' push _levelPointer',
				' push %buffer',
				' add',
				' store',
				'loopEnd',
				'',
				'moduleEnd',
			],
		},
		{
			code: [
				'module scale1',
				'; @pos -187 28',
				'float[] notes 12',
				'int length 7',
				'; @piano notes length 60',
				'init notes[0] 78.0',
				'init notes[1] 79.0',
				'init notes[2] 73.0',
				'init notes[3] 74.0',
				'init notes[4] 71.0',
				'init notes[5] 69.0',
				'init notes[6] 81.0',
				'moduleEnd',
			],
		},
	],
};

export default ericSaiteGenerator;
