import type { Project } from '@8f4e/editor-state-types';

const midiArpeggiator: Project = {
	codeBlocks: [
		{
			code: [
				'config',
				'; @pos -47 -25',
				'; @config runtime WebWorkerMIDIRuntime',
				'; ~sampleRate 50',
				'',
				'',
				'configEnd',
			],
		},
		{
			code: [
				'module chord1',
				'; @pos -43 -1',
				'float[] notes 12 48.0 52.0 55.0 64.0 67.0 60.0',
				'int length 6',
				'; @piano notes length 48',
				'moduleEnd',
			],
		},
		{
			code: [
				'module chord2',
				'; @pos 7 -1',
				'float[] notes 12 50.0 53.0 57.0 60.0 64.0 67.0',
				'int length 6',
				'; @piano notes length 48',
				'moduleEnd',
			],
		},
		{
			code: [
				'module clock',
				'; @pos 150 -38',
				'',
				'const HIGH 1',
				'const LOW 0',
				'',
				'int out',
				'',
				'push &out',
				'push out',
				'push HIGH',
				'equal',
				'if',
				'push LOW',
				'else',
				'push HIGH',
				'ifEnd int',
				'store',
				'',
				'moduleEnd',
			],
		},
		{
			code: [
				'module clockDivider',
				'; @pos 184 -38',
				'',
				'int default 4',
				'int* divider &default',
				'int* trigger &clock:out',
				'int out',
				'int counter',
				'',
				'; @watch out',
				'',
				'; Avoid remainder by zero',
				'push *divider',
				'push 0',
				'equal',
				'branchIfTrue 0',
				'',
				'push *trigger',
				'risingEdge',
				'if',
				'push &counter',
				'push counter',
				'push 1',
				'add',
				'store ',
				'ifEnd',
				'',
				'push counter',
				'push *divider',
				'ensureNonZero',
				'remainder',
				'push 0',
				'equal',
				'if',
				'push &out',
				'push *trigger',
				'store',
				'else',
				'push &out',
				'push 0',
				'store',
				'ifEnd',
				'',
				'moduleEnd',
			],
		},
		{
			code: [
				'module controls',
				'; @pos -4 -12',
				'',
				'int changeChord',
				'; @button changeChord',
				'int velocity 100',
				'int channel 1',
				'float minNote 48.0',
				'float maxNote 92.0',
				'',
				'moduleEnd',
			],
		},
		{
			code: [
				'module lengthMux',
				'; @pos 102 6',
				'',
				'int* in0 &chord1:length',
				'int* in1 &chord2:length',
				'int* in2',
				'int* in3',
				'int* in4',
				'int* in5',
				'int* in6',
				'int* in7',
				'',
				'int _length 2; default',
				'int* trigger &controls:changeChord',
				'int* length &_length',
				'',
				'int out',
				'',
				'int counter',
				'; @watch counter',
				'',
				'push *trigger',
				'risingEdge',
				'if',
				' ; Increment counter',
				'push &counter',
				'push counter',
				'push 1',
				'add',
				'store',
				'ifEnd',
				'',
				'; Guard',
				'push counter',
				'push *length',
				'greaterOrEqual',
				'if',
				'push &counter',
				'push 0',
				'store',
				'ifEnd',
				'',
				'push &out',
				' ; Calculate input address',
				'push &in0',
				'push counter',
				'push %in0',
				'mul',
				'add',
				'',
				' ; Load value',
				'load',
				'store',
				'',
				'moduleEnd',
			],
		},
		{
			code: [
				'module mapToRange2',
				'; @pos 99 -26',
				'',
				'const IN_RANGE_MIN -1.0',
				'const IN_RANGE_MAX 1.0',
				'',
				'float* in &triangle:out',
				'float* outRangeMin &controls:minNote',
				'float* outRangeMax &controls:maxNote',
				'float out',
				'',
				'; @watch out',
				'',
				'push &out',
				'push *in',
				'push IN_RANGE_MIN',
				'sub',
				'push IN_RANGE_MAX',
				'push IN_RANGE_MIN',
				'sub',
				'ensureNonZero',
				'div',
				'push *outRangeMax',
				'push *outRangeMin',
				'sub',
				'mul',
				'push *outRangeMin',
				'add',
				'store',
				'',
				'moduleEnd',
			],
		},
		{
			code: [
				'module midinoteout',
				'; @pos 226 6',
				'',
				'float* noteIn &quantizer:out',
				'int* channel &controls:channel',
				'int* gate &clockDivider:out',
				'int* velocity &controls:velocity',
				'int note ',
				'',
				'push &note',
				'push *noteIn',
				'castToInt',
				'store',
				'',
				'moduleEnd',
			],
		},
		{
			code: [
				'module notesMux',
				'; @pos 59 6',
				'',
				'int* in0 &chord1:notes',
				'int* in1 &chord2:notes',
				'int* in2',
				'int* in3',
				'int* in4',
				'int* in5',
				'int* in6',
				'int* in7',
				'',
				'int _length 2; default',
				'int* trigger &controls:changeChord',
				'int* length &_length',
				'',
				'int out',
				'',
				'int counter',
				'',
				'push *trigger',
				'risingEdge',
				'if',
				' ; Increment counter',
				'push &counter',
				'push counter',
				'push 1',
				'add',
				'store',
				'ifEnd',
				'',
				'; Guard',
				'push counter',
				'push *length',
				'greaterOrEqual',
				'if',
				'push &counter',
				'push 0',
				'store',
				'ifEnd',
				'',
				'push &out',
				' ; Calculate input address',
				'push &in0',
				'push counter',
				'push %in0',
				'mul',
				'add',
				'',
				' ; Load value',
				'load',
				'store',
				'',
				'moduleEnd',
			],
		},
		{
			code: [
				'module quantizer',
				'; @pos 184 6',
				'',
				'float* in &mapToRange2:out',
				'float* buffer &replicator:buffer',
				'int* length &replicator:length',
				'float out',
				'',
				'; @watch out',
				'',
				'float* _levelPointer',
				'float _difference',
				'float _smallestDiff 1000',
				'',
				'; @watch &_smallestDiff',
				'',
				'push &_smallestDiff',
				'push 1000.0',
				'store',
				'',
				'push &_levelPointer',
				'push buffer',
				'store',
				'',
				'loop',
				' ; Calculate difference ',
				' ; between the input and',
				' ; the current level.',
				'push &_difference',
				'push *_levelPointer',
				'push *in',
				'sub',
				'abs',
				'store',
				'',
				'push _difference',
				'push _smallestDiff',
				'lessOrEqual',
				'if',
				"  ; If it's actually smaller",
				'  ; than the smallest difference,',
				'  ; then update the smallest ',
				'  ; difference.',
				'push &_smallestDiff',
				'push _difference',
				'store',
				'  ; Save the current level value.',
				'push &out',
				'push *_levelPointer',
				'store',
				'ifEnd',
				'',
				' ; Guard',
				'push _levelPointer',
				'push buffer',
				'push *length',
				'push 1',
				'sub',
				'push %buffer',
				'mul',
				'add',
				'greaterOrEqual',
				'branchIfTrue 1 ',
				'',
				' ; Increment level pointer',
				'push &_levelPointer',
				'push _levelPointer',
				'push %buffer',
				'add',
				'store',
				'loopEnd',
				'',
				'moduleEnd',
			],
		},
		{
			code: [
				'module replicator',
				'; @pos 145 6',
				'',
				'const TIMES 3',
				'const OFFSET 24.0',
				'',
				'float** bufferIn &notesMux:out',
				'int** lengthIn &lengthMux:out',
				'float[] buffer 64 ; max size',
				'int length',
				'int _pointer',
				' ',
				'; @watch &buffer',
				'',
				'; @watch buffer[0]',
				'; @watch buffer[1]',
				'; @watch buffer[2]',
				'; @watch buffer[3]',
				'; @watch buffer[4]',
				'; @watch length',
				'',
				'; @plot &buffer length',
				'',
				'push &length',
				'push *lengthIn',
				'push TIMES',
				'mul',
				'store',
				'',
				'push &_pointer',
				'push 0',
				'store',
				'',
				'; To avoid remainder by zero',
				'push length',
				'push 0',
				'equal',
				'branchIfTrue 0',
				'',
				'loop ',
				' ; Calculate destination',
				' ; address',
				'push &buffer',
				'push _pointer',
				'push %buffer',
				'mul',
				'add',
				'',
				' ; Calculate source',
				' ; address',
				'push bufferIn',
				'load',
				'push _pointer',
				'push *lengthIn',
				'ensureNonZero',
				'remainder',
				'push %buffer',
				'mul',
				'add',
				'  ',
				'loadFloat',
				'',
				'push _pointer',
				'push *lengthIn',
				'ensureNonZero',
				'div',
				'castToFloat',
				'push OFFSET',
				'mul',
				'add',
				'',
				'store ; value to dst',
				'',
				' ; Guard',
				'push _pointer',
				'push length',
				'push 1',
				'sub',
				'greaterOrEqual',
				'branchIfTrue 1',
				' ',
				' ; Increment buffer pointer',
				'push &_pointer',
				'push _pointer',
				'push 1',
				'add',
				'store',
				'loopEnd',
				'',
				'moduleEnd',
			],
		},
		{
			code: [
				'module triangle',
				'; @pos 64 -36',
				'',
				'float default 0.5 ;Hz ',
				'float* frequency &default',
				'float out',
				'float direction 1 ',
				'',
				'push &out',
				'push out',
				'push *frequency',
				'push 2.0',
				'mul',
				'push SAMPLE_RATE',
				'castToFloat',
				'ensureNonZero',
				'div',
				'push direction',
				'mul',
				'add',
				'store',
				'',
				'push out',
				'push 1.0',
				'greaterThan',
				'if',
				'push &direction',
				'push -1.0',
				'store',
				'ifEnd',
				'',
				'push out',
				'push -1.0',
				'lessThan',
				'if',
				'push &direction',
				'push 1.0',
				'store',
				'ifEnd',
				'',
				'moduleEnd',
			],
		},
	],
};

export default midiArpeggiator;
