import type { Project } from '@8f4e/editor-state';

const midiArpeggiator2: Project = {
	codeBlocks: [
		{
			code: [
				'config',
				'; @pos -90 -12',
				'; @pos -130 5',
				'',
				'scope "memorySizeBytes"',
				'push 65536',
				'set',
				'popScope',
				'',
				'scope "runtimeSettings"',
				'scope "runtime"',
				'push "WebWorkerMIDIRuntime"',
				'set',
				'rescopeTop "sampleRate"',
				'push 50',
				'set',
				'popScope',
				'',
				'configEnd',
			],
		},
		{
			code: [
				'module bufferCombiner',
				'; @pos 34 5',
				'',
				'float* bufferA &chord1.notes',
				'int* lengthA &chord1.length',
				'float* bufferB &chord2.notes',
				'int* lengthB &mapToRange4.out',
				'',
				'float[] buffer 16',
				'int length',
				'',
				'int bufferPointer',
				'',
				'; Calculate combined length',
				'push &length',
				'push *lengthA',
				'push *lengthB',
				'add',
				'store',
				'',
				'; Reset buffer pointer',
				'push &bufferPointer',
				'push 0',
				'store',
				' ',
				'loop',
				' ; Guard ',
				' push bufferPointer',
				' push length',
				' greaterOrEqual',
				' branchIfTrue 1',
				' ',
				' ; Calculate destination',
				' ; buffer address',
				' push &buffer',
				' push bufferPointer',
				' push %buffer',
				' mul',
				' add',
				' ',
				' ; Calculate sorce',
				' ; buffer address',
				' push bufferPointer',
				' push *lengthA',
				' lessThan',
				' if int',
				'  push bufferA  ',
				'  push bufferPointer',
				'  push %bufferA',
				'  mul',
				'  add',
				' else',
				'  push bufferB',
				'  push bufferPointer',
				'  push *lengthA',
				'  sub',
				'  push %bufferB',
				'  mul',
				'  add',
				' ifEnd',
				'',
				' load ; value from src',
				' store ; value in dst',
				' ',
				' ; Increment buffer pointer',
				' push &bufferPointer',
				' push bufferPointer',
				' push 1',
				' add',
				' store',
				'loopEnd',
				'',
				'moduleEnd',
			],
		},
		{
			code: [
				'module chord1',
				'; @pos -19 4',
				'float[] notes 12',
				'int length 3',
				'; @piano notes length 48',
				'init notes[0] 48.0',
				'init notes[1] 55.0',
				'init notes[2] 52.0',
				'moduleEnd',
			],
		},
		{
			code: [
				'module chord2',
				'; @pos -19 17',
				'float[] notes 12',
				'int length 3',
				'; @piano notes length 48',
				'init notes[0] 67.0',
				'init notes[1] 60.0',
				'init notes[2] 65.0',
				'moduleEnd',
			],
		},
		{
			code: [
				'module clock',
				'; @pos 30 -41',
				'',
				'const HIGH 1',
				'const LOW 0',
				'',
				'int out',
				'',
				'push &out',
				'push out',
				'push HIGH',
				'equal',
				'if int',
				' push LOW',
				'else',
				' push HIGH',
				'ifEnd',
				'store',
				'',
				'moduleEnd',
			],
		},
		{
			code: [
				'module clockDivider',
				'; @pos 64 -41',
				'',
				'int default 8',
				'int* divider &default',
				'int* trigger &clock.out',
				'int out',
				'int counter',
				'',
				'; @debug out',
				'',
				'; Avoid remainder by zero',
				'push *divider',
				'push 0',
				'equal',
				'branchIfTrue 0',
				'',
				'push *trigger',
				'risingEdge',
				'if void',
				' push &counter',
				' push counter',
				' push 1',
				' add',
				' store ',
				'ifEnd',
				'',
				'push counter',
				'push *divider',
				'ensureNonZero',
				'remainder',
				'push 0',
				'equal',
				'if void',
				' push &out',
				' push *trigger',
				' store',
				'else',
				' push &out',
				' push 0',
				' store',
				'ifEnd',
				'',
				'moduleEnd',
			],
		},
		{
			code: [
				'module lcg',
				'; @pos -89 -31',
				'; Linear congruential ',
				'; generator',
				'',
				'const MULTIPLIER 1664525',
				'const INCREMENT 1013904223 ',
				'const MODULUS 65536 ; 2^16',
				'int seed 69420',
				'',
				'float out',
				'',
				'push &seed',
				' push MULTIPLIER',
				' push seed',
				' mul',
				' push INCREMENT',
				' add',
				' push MODULUS',
				' ensureNonZero',
				' remainder',
				'store',
				'',
				'push &out',
				' push seed',
				' castToFloat',
				' push MODULUS',
				' castToFloat',
				' ensureNonZero',
				' div ',
				'store',
				'',
				'moduleEnd',
			],
		},
		{
			code: [
				'module lcg2',
				'; @pos -125 -31',
				'; Linear congruential ',
				'; generator',
				'',
				'const MULTIPLIER 1664525',
				'const INCREMENT 1013904223 ',
				'const MODULUS 65536 ; 2^16',
				'int seed 69421',
				'',
				'float out',
				'',
				'push &seed',
				' push MULTIPLIER',
				' push seed',
				' mul',
				' push INCREMENT',
				' add',
				' push MODULUS',
				' ensureNonZero',
				' remainder',
				'store',
				'',
				'push &out',
				' push seed',
				' castToFloat',
				' push MODULUS',
				' castToFloat',
				' ensureNonZero',
				' div ',
				'store',
				'',
				'moduleEnd',
			],
		},
		{
			code: [
				'module mapToRange2',
				'; @pos -18 -31',
				'',
				'const IN_RANGE_MIN -1.0',
				'const IN_RANGE_MAX 1.0',
				'',
				'float min 48.0',
				'float max 92.0',
				'',
				'float* in &lcg.out',
				'float* outRangeMin &min',
				'float* outRangeMax &max',
				'float out',
				'',
				'; @debug out',
				'',
				'push &out',
				'push *in',
				'push IN_RANGE_MIN',
				'sub',
				'push IN_RANGE_MAX',
				'push IN_RANGE_MIN',
				'sub',
				'ensureNonZero',
				'div',
				'push *outRangeMax',
				'push *outRangeMin',
				'sub',
				'mul',
				'push *outRangeMin',
				'add',
				'store',
				'',
				'moduleEnd',
			],
		},
		{
			code: [
				'module mapToRange4',
				'; @pos -55 6',
				'',
				'const IN_RANGE_MIN -1.0',
				'const IN_RANGE_MAX 1.0',
				'const OUT_RANGE_MIN 0.0',
				'const OUT_RANGE_MAX 4.0',
				'',
				'float* in &triangle2.out',
				'int out',
				'',
				'; @debug out',
				'',
				'push &out',
				'push *in',
				'push IN_RANGE_MIN',
				'sub',
				'push IN_RANGE_MAX',
				'push IN_RANGE_MIN',
				'sub',
				'ensureNonZero',
				'div',
				'push OUT_RANGE_MAX',
				'push OUT_RANGE_MIN',
				'sub',
				'mul',
				'push OUT_RANGE_MIN',
				'add',
				'round',
				'castToInt',
				'store',
				'',
				'moduleEnd',
			],
		},
		{
			code: [
				'module mapToRange5',
				'; @pos -53 -31',
				'',
				'const IN_RANGE_MIN -1.0',
				'const IN_RANGE_MAX 1.0',
				'const OUT_RANGE_MIN 10.0',
				'const OUT_RANGE_MAX 127.0',
				'',
				'float* in &lcg2.out',
				'int out',
				'',
				'; @debug out',
				'',
				'push &out',
				'push *in',
				'push IN_RANGE_MIN',
				'sub',
				'push IN_RANGE_MAX',
				'push IN_RANGE_MIN',
				'sub',
				'ensureNonZero',
				'div',
				'push OUT_RANGE_MAX',
				'push OUT_RANGE_MIN',
				'sub',
				'mul',
				'push OUT_RANGE_MIN',
				'add',
				'round',
				'castToInt',
				'store',
				'',
				'moduleEnd',
			],
		},
		{
			code: [
				'module midinoteout',
				'; @pos 20 -13',
				'',
				'float* noteIn &quantizer.out',
				'int channel 1',
				'int* gate &clockDivider.out',
				'int* velocity &mapToRange5.out',
				'int note ',
				'',
				'push &note',
				'push *noteIn',
				'castToInt',
				'store',
				'',
				'moduleEnd',
			],
		},
		{
			code: [
				'module quantizer',
				'; @pos 119 5',
				'',
				'float* in &mapToRange2.out',
				'float* buffer &replicator.buffer',
				'int* length &replicator.length',
				'float out',
				'',
				'; @debug out',
				'',
				'float* _levelPointer',
				'float _difference',
				'float _smallestDiff 1000',
				'',
				'; @debug &_smallestDiff',
				'',
				'push &_smallestDiff',
				'push 1000.0',
				'store',
				'',
				'push &_levelPointer',
				'push buffer',
				'store',
				'',
				'loop',
				' ; Calculate difference ',
				' ; between the input and',
				' ; the current level.',
				' push &_difference',
				' push *_levelPointer',
				' push *in',
				' sub',
				' abs',
				' store',
				'',
				' push _difference',
				' push _smallestDiff',
				' lessOrEqual',
				' if void',
				"  ; If it's actually smaller",
				'  ; than the smallest difference,',
				'  ; then update the smallest ',
				'  ; difference.',
				'  push &_smallestDiff',
				'  push _difference',
				'  store',
				'  ; Save the current level value.',
				'  push &out',
				'  push *_levelPointer',
				'  store',
				' ifEnd',
				'',
				' ; Guard',
				' push _levelPointer',
				' push buffer',
				' push *length',
				' push 1',
				' sub',
				' push %buffer',
				' mul',
				' add',
				' greaterOrEqual',
				' branchIfTrue 1 ',
				'',
				' ; Increment level pointer',
				' push &_levelPointer',
				' push _levelPointer',
				' push %buffer',
				' add',
				' store',
				'loopEnd',
				'',
				'moduleEnd',
			],
		},
		{
			code: [
				'module replicator',
				'; @pos 72 5',
				'',
				'const TIMES 3',
				'const OFFSET 24.0',
				'',
				'float* bufferIn &bufferCombiner.buffer',
				'int* lengthIn &bufferCombiner.length',
				'float[] buffer 64 ; max size',
				'int length',
				'int _pointer',
				' ',
				'; @debug length',
				'',
				'; @plot buffer 0 127 length',
				'',
				'push &length',
				'push *lengthIn',
				'push TIMES',
				'mul',
				'store',
				'',
				'push &_pointer',
				'push 0',
				'store',
				'',
				'; To avoid remainder by zero',
				'push length',
				'push 0',
				'equal',
				'branchIfTrue 0',
				'',
				'loop ',
				' ; Calculate destination',
				' ; address',
				' push &buffer',
				' push _pointer',
				' push %buffer',
				' mul',
				' add',
				'',
				' ; Calculate source',
				' ; address',
				' push bufferIn',
				' push _pointer',
				' push *lengthIn',
				' ensureNonZero',
				' remainder',
				' push %buffer',
				' mul',
				' add',
				'  ',
				' loadFloat',
				'',
				' push _pointer',
				' push *lengthIn',
				' ensureNonZero',
				' div',
				' castToFloat',
				' push OFFSET',
				' mul',
				' add',
				'',
				' store ; value to dst',
				'',
				' ; Guard',
				' push _pointer',
				' push length',
				' push 1',
				' sub',
				' greaterOrEqual',
				' branchIfTrue 1',
				' ',
				' ; Increment buffer pointer',
				' push &_pointer',
				' push _pointer',
				' push 1',
				' add',
				' store',
				'loopEnd',
				'',
				'moduleEnd',
			],
		},
		{
			code: [
				'module triangle2',
				'; @pos -89 2',
				'',
				'float default 0.3 ;Hz ',
				'float* frequency &default',
				'float out',
				'float direction 1 ',
				'',
				'push &out',
				'push out',
				'push *frequency',
				'push 2.0',
				'mul',
				'push SAMPLE_RATE',
				'castToFloat',
				'ensureNonZero',
				'div',
				'push direction',
				'mul',
				'add',
				'store',
				'',
				'push out',
				'push 1.0',
				'greaterThan',
				'if void',
				' push &direction',
				' push -1.0',
				' store',
				'ifEnd',
				'',
				'push out',
				'push -1.0',
				'lessThan',
				'if void',
				' push &direction',
				' push 1.0',
				' store',
				'ifEnd',
				'',
				'moduleEnd',
			],
		},
	],
	viewport: { gridCoordinates: { x: -90, y: -12 } },
};

export default midiArpeggiator2;
