import type { Project } from '@8f4e/editor-state';

const project: Project = {
	codeBlocks: [
		{
			code: [
				'config',
				'; @pos -50 -6',
				'',
				'scope "memorySizeBytes"',
				'push 65536',
				'set',
				'popScope',
				'',
				'scope "runtimeSettings"',
				'scope "runtime"',
				'push "WebWorkerMIDIRuntime"',
				'set',
				'rescopeTop "sampleRate"',
				'push 50',
				'set',
				'popScope',
				'popScope',
				'',
				'configEnd',
			],
		},
		{
			code: [
				'module chord',
				'; @pos -12 -6',
				'float[] notes 12',
				'int notesCount 6',
				'; @piano notes notesCount 36',
				'init notes[0] 36.0',
				'init notes[1] 40.0',
				'init notes[2] 43.0',
				'init notes[3] 48.0',
				'init notes[4] 55.0',
				'init notes[5] 52.0',
				'moduleEnd',
			],
		},
		{
			code: [
				'module chord2',
				'; @pos 38 -6',
				'float[] notes 12',
				'int notesCount 6',
				'; @piano notes notesCount 36',
				'init notes[0] 45.0',
				'init notes[1] 57.0',
				'init notes[2] 38.0',
				'init notes[3] 41.0',
				'init notes[4] 50.0',
				'init notes[5] 53.0',
				'moduleEnd',
			],
		},
		{
			code: [
				'module chord3',
				'; @pos -12 11',
				'float[] notes 12',
				'int notesCount 5',
				'; @piano notes notesCount 36',
				'init notes[0] 50.0',
				'init notes[1] 47.0',
				'init notes[2] 43.0',
				'init notes[3] 38.0',
				'init notes[4] 55.0',
				'moduleEnd',
			],
		},
		{
			code: [
				'module chord4',
				'; @pos 38 11',
				'float[] notes 12',
				'int notesCount 2',
				'; @piano notes notesCount 36',
				'init notes[0] 41.0',
				'init notes[1] 38.0',
				'moduleEnd',
			],
		},
		{
			code: [
				'module clock',
				'; @pos 31 40',
				'',
				'const HIGH 1',
				'const LOW 0',
				'',
				'int out',
				'',
				'push &out',
				'push out',
				'push HIGH',
				'equal',
				'if int',
				' push LOW',
				'else',
				' push HIGH',
				'ifEnd',
				'store',
				'',
				'moduleEnd',
			],
		},
		{
			code: [
				'module clockDiv',
				'; @pos 67 40',
				'',
				'int default 128',
				'int* divider &default',
				'int* trigger &clock.out',
				'int out',
				'int counter',
				'',
				'push *trigger',
				'risingEdge',
				'if void',
				' push &counter',
				' push counter',
				' push 1',
				' add',
				' store ',
				'ifEnd',
				'',
				'push counter',
				'push *divider',
				'ensureNonZero',
				'remainder',
				'push 0',
				'equal',
				'if void',
				' push &out',
				' push *trigger',
				' store',
				'else',
				' push &out',
				' push 0',
				' store',
				'ifEnd',
				'',
				'moduleEnd',
			],
		},
		{
			code: [
				'module clockDiv2',
				'; @pos 31 61',
				'',
				'int default 4',
				'int* divider &default',
				'int* trigger &clock.out',
				'int out',
				'int counter',
				'',
				'push *trigger',
				'risingEdge',
				'if void',
				' push &counter',
				' push counter',
				' push 1',
				' add',
				' store ',
				'ifEnd',
				'',
				'push *divider',
				'push 0',
				'equal',
				'branchIfTrue 0',
				'',
				'push counter',
				'push *divider',
				'ensureNonZero',
				'remainder',
				'push 0',
				'equal',
				'if void',
				' push &out',
				' push *trigger',
				' store',
				'else',
				' push &out',
				' push 0',
				' store',
				'ifEnd',
				'',
				'moduleEnd',
			],
		},
		{
			code: [
				'module float2Int',
				'; @pos 69 77',
				'',
				'float* in &seqMuxF.out',
				'int out',
				'',
				'; @debug out',
				'',
				'push &out',
				'push *in',
				'castToInt',
				'store',
				'',
				'moduleEnd',
			],
		},
		{
			code: [
				'module lcg',
				'; @pos 119 -53',
				'; Linear congruential ',
				'; generator',
				'',
				'const MULTIPLIER 1664525',
				'const INCREMENT 1013904223 ',
				'const MODULUS 65536 ; 2^16',
				'int seed 69420',
				'',
				'float out',
				'',
				'push &seed',
				' push MULTIPLIER',
				' push seed',
				' mul',
				' push INCREMENT',
				' add',
				' push MODULUS',
				' ensureNonZero',
				' remainder',
				'store',
				'',
				'push &out',
				' push seed',
				' castToFloat',
				' push MODULUS',
				' castToFloat',
				' ensureNonZero',
				' div ',
				'store',
				'',
				'moduleEnd',
			],
		},
		{
			code: [
				'module midinoteout',
				'; @pos 91 19',
				'',
				'int* note &float2Int.out',
				'int channel 1',
				'int* gate &clockDiv2.out',
				'int velocity 127',
				'',
				'moduleEnd',
			],
		},
		{
			code: [
				'module quantizer',
				'; @pos 181 6',
				'',
				'float* in &signal.out',
				'float* buffer &replicator.buffer',
				'int* length &replicator.length',
				'float out ',
				'',
				'float* _levelPointer',
				'float _difference',
				'float _smallestDiff 1000',
				'',
				'push &_smallestDiff',
				'push 1000.0',
				'store',
				'',
				'push &_levelPointer',
				'push buffer',
				'store',
				'',
				'loop',
				' ; Calculate difference ',
				' ; between the input and',
				' ; the current level.',
				' push &_difference',
				' push *_levelPointer',
				' push *in',
				' sub',
				' abs',
				' store',
				'',
				' push _difference',
				' push _smallestDiff',
				' lessOrEqual',
				' if void',
				"  ; If it's actually smaller",
				'  ; than the smallest difference,',
				'  ; then update the smallest ',
				'  ; difference.',
				'  push &_smallestDiff',
				'  push _difference',
				'  store',
				'  ; Save the current level value.',
				'  push &out',
				'  push *_levelPointer',
				'  store',
				' ifEnd',
				'',
				' ; Guard',
				' push _levelPointer',
				' push buffer',
				' push *length',
				' push 1',
				' sub',
				' push %buffer',
				' mul',
				' add',
				' greaterOrEqual',
				' branchIfTrue 1 ',
				'',
				' ; Increment level pointer',
				' push &_levelPointer',
				' push _levelPointer',
				' push %buffer',
				' add',
				' store',
				'loopEnd',
				'',
				'moduleEnd',
			],
		},
		{
			code: [
				'module quantizer2',
				'; @pos 263 6',
				'',
				'float* in &signal.out',
				'float* buffer &replicator2.buffer',
				'int* length &replicator2.length',
				'float out',
				'',
				'float* _levelPointer',
				'float _difference',
				'float _smallestDiff 1000',
				'',
				'push &_smallestDiff',
				'push 1000.0',
				'store',
				'',
				'push &_levelPointer',
				'push buffer',
				'store',
				'',
				'loop',
				' ; Calculate difference ',
				' ; between the input and',
				' ; the current level.',
				' push &_difference',
				' push *_levelPointer',
				' push *in',
				' sub',
				' abs',
				' store',
				'',
				' push _difference',
				' push _smallestDiff',
				' lessOrEqual',
				' if void',
				"  ; If it's actually smaller",
				'  ; than the smallest difference,',
				'  ; then update the smallest ',
				'  ; difference.',
				'  push &_smallestDiff',
				'  push _difference',
				'  store',
				'  ; Save the current level value.',
				'  push &out',
				'  push *_levelPointer',
				'  store',
				' ifEnd',
				'',
				' ; Guard',
				' push _levelPointer',
				' push buffer',
				' push *length',
				' push 1',
				' sub',
				' push %buffer',
				' mul',
				' add',
				' greaterOrEqual',
				' branchIfTrue 1 ',
				'',
				' ; Increment level pointer',
				' push &_levelPointer',
				' push _levelPointer',
				' push %buffer',
				' add',
				' store',
				'loopEnd',
				'',
				'moduleEnd',
			],
		},
		{
			code: [
				'module quantizer3',
				'; @pos 346 6',
				'',
				'float* in &signal.out',
				'float* buffer &replicator3.buffer',
				'int* length &replicator3.length',
				'float out',
				'',
				'float* _levelPointer',
				'float _difference',
				'float _smallestDiff 1000',
				'',
				'push &_smallestDiff',
				'push 1000.0',
				'store',
				'',
				'push &_levelPointer',
				'push buffer',
				'store',
				'',
				'loop',
				' ; Calculate difference ',
				' ; between the input and',
				' ; the current level.',
				' push &_difference',
				' push *_levelPointer',
				' push *in',
				' sub',
				' abs',
				' store',
				'',
				' push _difference',
				' push _smallestDiff',
				' lessOrEqual',
				' if void',
				"  ; If it's actually smaller",
				'  ; than the smallest difference,',
				'  ; then update the smallest ',
				'  ; difference.',
				'  push &_smallestDiff',
				'  push _difference',
				'  store',
				'  ; Save the current level value.',
				'  push &out',
				'  push *_levelPointer',
				'  store',
				' ifEnd',
				'',
				' ; Guard',
				' push _levelPointer',
				' push buffer',
				' push *length',
				' push 1',
				' sub',
				' push %buffer',
				' mul',
				' add',
				' greaterOrEqual',
				' branchIfTrue 1 ',
				'',
				' ; Increment level pointer',
				' push &_levelPointer',
				' push _levelPointer',
				' push %buffer',
				' add',
				' store',
				'loopEnd',
				'',
				'moduleEnd',
			],
		},
		{
			code: [
				'module quantizer4',
				'; @pos 429 6',
				'',
				'float* in &signal.out',
				'float* buffer &replicator4.buffer',
				'int* length &replicator4.length',
				'float out',
				'',
				'float* _levelPointer',
				'float _difference',
				'float _smallestDiff 1000',
				'',
				'push &_smallestDiff',
				'push 1000.0',
				'store',
				'',
				'push &_levelPointer',
				'push buffer',
				'store',
				'',
				'loop',
				' ; Calculate difference ',
				' ; between the input and',
				' ; the current level.',
				' push &_difference',
				' push *_levelPointer',
				' push *in',
				' sub',
				' abs',
				' store',
				'',
				' push _difference',
				' push _smallestDiff',
				' lessOrEqual',
				' if void',
				"  ; If it's actually smaller",
				'  ; than the smallest difference,',
				'  ; then update the smallest ',
				'  ; difference.',
				'  push &_smallestDiff',
				'  push _difference',
				'  store',
				'  ; Save the current level value.',
				'  push &out',
				'  push *_levelPointer',
				'  store',
				' ifEnd',
				'',
				' ; Guard',
				' push _levelPointer',
				' push buffer',
				' push *length',
				' push 1',
				' sub',
				' push %buffer',
				' mul',
				' add',
				' greaterOrEqual',
				' branchIfTrue 1 ',
				'',
				' ; Increment level pointer',
				' push &_levelPointer',
				' push _levelPointer',
				' push %buffer',
				' add',
				' store',
				'loopEnd',
				'',
				'moduleEnd',
			],
		},
		{
			code: [
				'module replicator',
				'; @pos 141 6',
				'',
				'const TIMES 2',
				'const OFFSET 24.0',
				'',
				'float* bufferIn &chord.notes',
				'int* lengthIn &chord.notesCount',
				'float[] buffer 64 ; max size',
				'int length',
				'int _pointer',
				'',
				'; @debug length',
				'',
				'; @debug buffer[10]',
				'',
				'; @plot buffer 0 200 length',
				'',
				'push &length',
				'push *lengthIn',
				'push TIMES',
				'mul',
				'store',
				'',
				'push &_pointer',
				'push 0',
				'store',
				'',
				'loop',
				' ; Guard',
				' push _pointer',
				' push length',
				' greaterOrEqual',
				' branchIfTrue 1 ',
				' ',
				' ; Calculate destination',
				' ; address',
				' push &buffer',
				' push _pointer',
				' push %buffer',
				' mul',
				' add',
				'',
				' ; Calculate source',
				' ; address',
				' push bufferIn',
				' push _pointer',
				' push *lengthIn',
				' ensureNonZero',
				' remainder',
				' push %buffer',
				' mul',
				' add',
				' ',
				' loadFloat ; value from src',
				' ',
				' push _pointer',
				' push *lengthIn',
				' ensureNonZero',
				' div',
				' castToFloat',
				' push OFFSET',
				' mul',
				' add',
				'',
				' store ; value to dst',
				' ',
				' ; Increment buffer pointer',
				' push &_pointer',
				' push _pointer',
				' push 1',
				' add',
				' store',
				'loopEnd',
				'',
				'moduleEnd',
			],
		},
		{
			code: [
				'module replicator2',
				'; @pos 223 6',
				'',
				'const TIMES 2',
				'const OFFSET 24.0',
				'',
				'float* bufferIn &chord2.notes',
				'int* lengthIn &chord2.notesCount',
				'float[] buffer 64 ; max size',
				'int length',
				'int _pointer',
				'',
				'; @plot buffer 0 127 length',
				'',
				'push &length',
				'push *lengthIn',
				'push TIMES',
				'mul',
				'store',
				'',
				'push &_pointer',
				'push 0',
				'store',
				'',
				'loop',
				' ; Guard',
				' push _pointer',
				' push length',
				' greaterOrEqual',
				' branchIfTrue 1 ',
				' ',
				' ; Calculate destination',
				' ; address',
				' push &buffer',
				' push _pointer',
				' push %buffer',
				' mul',
				' add',
				'',
				' ; Calculate source',
				' ; address',
				' push bufferIn',
				' push _pointer',
				' push *lengthIn',
				' ensureNonZero',
				' remainder',
				' push %buffer',
				' mul',
				' add',
				' ',
				' loadFloat ; value from src',
				' ',
				' push _pointer',
				' push *lengthIn',
				' ensureNonZero',
				' div',
				' castToFloat',
				' push OFFSET',
				' mul',
				' add',
				'',
				' store ; value to dst',
				' ',
				' ; Increment buffer pointer',
				' push &_pointer',
				' push _pointer',
				' push 1',
				' add',
				' store',
				'loopEnd',
				'',
				'moduleEnd',
			],
		},
		{
			code: [
				'module replicator3',
				'; @pos 305 6',
				'',
				'const TIMES 2',
				'const OFFSET 24.0',
				'',
				'float* bufferIn &chord3.notes',
				'int* lengthIn &chord3.notesCount',
				'float[] buffer 64 ; max size',
				'int length',
				'int _pointer',
				'',
				'; @plot buffer 0 127 length',
				'',
				'push &length',
				'push *lengthIn',
				'push TIMES',
				'mul',
				'store',
				'',
				'push &_pointer',
				'push 0',
				'store',
				'',
				'loop',
				' ; Guard',
				' push _pointer',
				' push length',
				' greaterOrEqual',
				' branchIfTrue 1 ',
				' ',
				' ; Calculate destination',
				' ; address',
				' push &buffer',
				' push _pointer',
				' push %buffer',
				' mul',
				' add',
				'',
				' ; Calculate source',
				' ; address',
				' push bufferIn',
				' push _pointer',
				' push *lengthIn',
				' ensureNonZero',
				' remainder',
				' push %buffer',
				' mul',
				' add',
				' ',
				' loadFloat ; value from src',
				' ',
				' push _pointer',
				' push *lengthIn',
				' ensureNonZero',
				' div',
				' castToFloat',
				' push OFFSET',
				' mul',
				' add',
				'',
				' store ; value to dst',
				' ',
				' ; Increment buffer pointer',
				' push &_pointer',
				' push _pointer',
				' push 1',
				' add',
				' store',
				'loopEnd',
				'',
				'moduleEnd',
			],
		},
		{
			code: [
				'module replicator4',
				'; @pos 388 6',
				'',
				'const TIMES 4',
				'const OFFSET 24.0',
				'',
				'float* bufferIn &chord4.notes',
				'int* lengthIn &chord4.notesCount',
				'float[] buffer 64 ; max size',
				'int length',
				'int _pointer',
				'',
				'; @plot buffer 0 127 length',
				'',
				'push &length',
				'push *lengthIn',
				'push TIMES',
				'mul',
				'store',
				'',
				'push &_pointer',
				'push 0',
				'store',
				'',
				'loop',
				' ; Guard',
				' push _pointer',
				' push length',
				' greaterOrEqual',
				' branchIfTrue 1 ',
				' ',
				' ; Calculate destination',
				' ; address',
				' push &buffer',
				' push _pointer',
				' push %buffer',
				' mul',
				' add',
				'',
				' ; Calculate source',
				' ; address',
				' push bufferIn',
				' push _pointer',
				' push *lengthIn',
				' ensureNonZero',
				' remainder',
				' push %buffer',
				' mul',
				' add',
				' ',
				' loadFloat ; value from src',
				' ',
				' push _pointer',
				' push *lengthIn',
				' ensureNonZero',
				' div',
				' castToFloat',
				' push OFFSET',
				' mul',
				' add',
				'',
				' store ; value to dst',
				' ',
				' ; Increment buffer pointer',
				' push &_pointer',
				' push _pointer',
				' push 1',
				' add',
				' store',
				'loopEnd',
				'',
				'moduleEnd',
			],
		},
		{
			code: [
				'module sawSignedFloat',
				'; @pos 85 -53',
				'',
				'float default 0.7 ;Hz ',
				'float* frequency &default',
				'float out',
				'',
				'push &out',
				'push out',
				'push *frequency',
				'push SAMPLE_RATE',
				'castToFloat',
				'ensureNonZero',
				'div',
				'add',
				'store',
				'',
				'push out',
				'push 1.0',
				'greaterThan',
				'if void',
				' push &out',
				' push 0',
				' store',
				'ifEnd',
				'',
				'moduleEnd',
			],
		},
		{
			code: [
				'module seqMuxF',
				'; @pos 104 40',
				'',
				'float* in0 &quantizer.out',
				'float* in1 &quantizer2.out',
				'float* in2 &quantizer3.out',
				'float* in3 &quantizer4.out',
				'float* in4',
				'float* in5',
				'float* in6',
				'float* in7',
				'',
				'int _length 3 ; default',
				'int* trigger &clockDiv.out',
				'int* length &_length',
				'',
				'float out',
				'',
				'int counter',
				'',
				'; @debug counter',
				'; @debug out',
				'',
				'push *trigger',
				'risingEdge',
				'if void ',
				' ; Increment counter',
				' push &counter',
				'  push counter',
				'  push 1',
				'  add',
				' store',
				'ifEnd',
				'',
				'; Guard',
				'push counter',
				'push *length',
				'greaterOrEqual',
				'if void',
				' push &counter',
				'  push 0',
				' store',
				'ifEnd',
				'',
				'push &out',
				' ; Calculate input address',
				' push &in0',
				' push counter',
				' push %in0',
				' mul',
				' add',
				'',
				' ; Load value',
				' load',
				' load',
				'store',
				'',
				'moduleEnd',
			],
		},
		{
			code: [
				'module seqMuxF2',
				'; @pos 157 -54',
				'',
				'float* in0 &lcg.out',
				'float* in1 &lcg.out',
				'float* in2 &triangleSignedFloat.out',
				'float* in3 &lcg.out',
				'float* in4 &lcg.out',
				'float* in5 &lcg.out',
				'float* in6 &triangleSignedFloat.out',
				'float* in7',
				'',
				'int _length 7 ; default',
				'int* trigger &clockDiv.out',
				'int* length &_length',
				'',
				'float out',
				'',
				'int counter',
				'',
				'; @debug counter',
				'; @debug out',
				'',
				'push *trigger',
				'risingEdge',
				'if void ',
				' ; Increment counter',
				' push &counter',
				'  push counter',
				'  push 1',
				'  add',
				' store',
				'ifEnd',
				'',
				'; Guard',
				'push counter',
				'push *length',
				'greaterOrEqual',
				'if void',
				' push &counter',
				'  push 0',
				' store',
				'ifEnd',
				'',
				'push &out',
				' ; Calculate input address',
				' push &in0',
				' push counter',
				' push %in0',
				' mul',
				' add',
				'',
				' ; Load value',
				' load',
				' load',
				'store',
				'',
				'moduleEnd',
			],
		},
		{
			code: [
				'module signal',
				'; @pos 201 -41',
				'',
				'float* in &seqMuxF2.out',
				'float out',
				'',
				'; @debug out',
				'',
				'push &out',
				'push *in',
				'push 1.0',
				'add',
				'push 2.0',
				'ensureNonZero',
				'div',
				'push 54.0',
				'mul',
				'',
				'push 24.0',
				'add',
				'',
				'store',
				'',
				'moduleEnd',
			],
		},
		{
			code: [
				'module triangleSignedFloat',
				'; @pos 49 -53',
				'',
				'float default 1 ;Hz ',
				'float* frequency &default',
				'float out',
				'float direction 1 ',
				'',
				'push &out',
				'push out',
				'push *frequency',
				'push 2.0',
				'mul',
				'push SAMPLE_RATE',
				'castToFloat',
				'ensureNonZero',
				'div',
				'push direction',
				'mul',
				'add',
				'store',
				'',
				'push out',
				'push 1.0',
				'greaterThan',
				'if void',
				' push &direction',
				' push -1.0',
				' store',
				'ifEnd',
				'',
				'push out',
				'push -1.0',
				'lessThan',
				'if void',
				' push &direction',
				' push 1.0',
				' store',
				'ifEnd',
				'',
				'moduleEnd',
			],
		},
	],
};

export default project;
