import { defaultFeatureFlags } from './featureFlags';

export default function createDefaultState() {
	return {
		compiler: {
			isCompiling: false,
			compiledModules: {},
		},
		graphicHelper: {
			codeBlocks: [],
			entryOutlines: [],
			viewportAnchoredCodeBlocks: [],
			textureCacheEpoch: 0,
			nextCodeBlockCreationIndex: 0,
			outputsByWordAddress: new Map(),
			showHiddenCodeBlocks: false,
			selectedCodeBlockForProgrammaticEdit: undefined,
		},
		contextMenu: {
			highlightedItem: 0,
			itemWidth: 200,
			items: [],
			open: false,
			x: 0,
			y: 0,
			menuStack: [],
		},
		postProcessEffects: [],
		backgroundEffects: [],
		info: {
			compiler: {
				isCompiling: false,
				compilationTimeMs: 0,
				wasmByteCodeBytes: 0,
				requiredMemoryBytes: 0,
				allocatedMemoryBytes: 0,
				allocatedPages: 0,
				memoryUsagePercent: 0,
				astCacheHits: 0,
				astCacheMisses: 0,
				memoryReinitialized: false,
			},
		},
		tooltip: {
			text: [],
			characters: [],
			colors: [],
			lineCount: 0,
			widthChars: 0,
			layout: {
				horizontalPadding: 0,
				width: 0,
				height: 0,
				x: 0,
				y: 0,
				lineX: 0,
			},
			highlights: [],
			liveValues: [],
		},
		featureFlags: defaultFeatureFlags,
		editorMode: 'view' as const,
		editorConfig: {},
		editorConfigValidators: {},
		editorConfigSchemaContributions: {},
		historyStack: [],
		redoStack: [],
		storageQuota: { usedBytes: 0, totalBytes: 0 },
		binaryAssets: [],
		codeErrors: {
			compilationErrors: [],
			editorDirectiveErrors: [],
			shaderErrors: [],
		},
		console: {
			logs: [],
			maxLogs: 100,
		},
		globalEditorDirectives: {},
		runtime: {
			values: {},
		},
		dialog: {
			id: '',
			text: '',
			wrappedText: [''],
			title: '',
			buttons: [],
			width: 0,
			height: 0,
			x: 0,
			y: 0,
		},
		dialogStack: [],
		viewport: {
			x: 0,
			y: 0,
			width: 0,
			height: 0,
			roundedHeight: 0,
			roundedWidth: 0,
			vGrid: 8,
			hGrid: 16,
			borderLineCoordinates: {
				top: { startX: 0, startY: 0, endX: 0, endY: 0 },
				right: { startX: 0, startY: 0, endX: 0, endY: 0 },
				bottom: { startX: 0, startY: 0, endX: 0, endY: 0 },
				left: { startX: 0, startY: 0, endX: 0, endY: 0 },
			},
			center: { x: 0, y: 0 },
		},
		viewportAnimation: {
			startX: 0,
			startY: 0,
			targetX: 0,
			targetY: 0,
			active: false,
			durationMs: 500,
		},
		presentation: {
			canPresent: false,
			activeStopIndex: 0,
			totalStops: 0,
			remainingMs: 0,
			currentStopDurationMs: 0,
			deadlineAt: undefined,
		},
	};
}
