export const projects = [
	{
		id: 'stack-operations',
		title: 'Stack operations',
		description: 'Follow numbers through the stack and see how arithmetic instructions work.',
		path: 'misc/landingPageDemo1.8f4e',
	},
	{
		id: 'interactive-controls',
		title: 'Interactive controls',
		description: 'Use sliders, switches and plots directly inside the running program.',
		path: 'misc/landingPageDemo4.8f4e',
	},
	{
		id: 'sr-latch',
		title: 'SR latch',
		description: 'Set and reset a memory circuit built from logic gates, and watch its state change.',
		path: 'digital/bistableMultivibrators.8f4e',
	},
	{
		id: 'random-generators',
		title: 'Random generators',
		description: 'Explore pseudorandom number generation and inspect the output in a plot.',
		path: 'misc/randomGenerators.8f4e',
	},
	{
		id: 'mono-synth',
		title: 'Keyboard synthesizer',
		description: 'Play a monophonic synthesizer using a physical keyboard.',
		path: 'audio/keyboardControlledMonoSynth.8f4e',
	},
	{
		id: 'pointers',
		title: 'Pointers and wires',
		description: 'Follow memory addresses through pointers and see their connections drawn as wires.',
		path: 'misc/landingPageDemo2.8f4e',
	},
	{
		id: 'memory-layout',
		title: 'Memory layout',
		description: 'Inspect adjacent memory addresses and step through them with a pointer.',
		path: 'misc/landingPageDemo3.8f4e',
	},
	{
		id: 'standalone-counter',
		title: 'Standalone counter',
		description: 'Start with a minimal program that increments a counter once per second in a worker.',
		path: 'misc/standaloneProject.8f4e',
	},
	{
		id: 'audio-buffer',
		title: 'Audio buffer',
		description: 'Generate a sine wave and write its samples into a circular audio buffer.',
		path: 'audio/audioBuffer.8f4e',
	},
	{
		id: 'audio-loopback',
		title: 'Audio loopback',
		description: 'Route incoming audio to the left and right outputs through shared audio buffers.',
		path: 'audio/audioLoopback.8f4e',
	},
	{
		id: 'sample-player',
		title: 'Sample player',
		description: 'Loop an external 8-bit PCM sample and follow the playhead through memory.',
		path: 'audio/samplePlayer.8f4e',
	},
	{
		id: 'variable-speed-player',
		title: 'Variable-speed sample player',
		description: 'Change playback speed using a floating-point playhead that advances by fractional steps.',
		path: 'audio/samplePlayerVariableSpeed.8f4e',
	},
	{
		id: 'cyclic-timestretch',
		title: 'Cyclic time stretch',
		description: 'Stretch a sample by repeating and crossfading short cycles while preserving their playback pitch.',
		path: 'audio/cyclicTimestretch.8f4e',
	},
	{
		id: 'minblep',
		title: 'minBLEP smoothing',
		description: 'Compare a pulse sample before and after a band-limited step correction smooths its discontinuities.',
		path: 'audio/minBLEP.8f4e',
	},
	{
		id: 'fm-synth',
		title: 'Six-operator FM synthesizer',
		description: 'Play a keyboard-controlled FM synthesizer with six operators and individual envelopes.',
		path: 'audio/keyboardController6OperatorFMSynth.8f4e',
	},
	{
		id: 'clouds-reverb',
		title: 'Clouds reverb',
		description: 'Explore a stereo reverb built from modulated delays, diffusers and feedback paths.',
		path: 'audio/MICloudsReverb.8f4e',
	},
	{
		id: 'clouds-reverb-grouped',
		title: 'Clouds reverb: grouped',
		description: 'Follow a sample through a reverb whose processing modules are organized into a group.',
		path: 'audio/MICloudsReverbGrouped.8f4e',
	},
	{
		id: 'clouds-reverb-tweakable',
		title: 'Clouds reverb: tweakable',
		description: 'Shape the reverb with sliders for decay, diffusion, damping and delay modulation.',
		path: 'audio/MICloudsReverbTweakable.8f4e',
	},
	{
		id: 'granular-sampler',
		title: 'Granular sampler',
		description: 'Explore sample playback driven by a clock, random positions and modulation, with stereo reverb.',
		path: 'audio/granularSampler.8f4e',
	},
	{
		id: 'risen',
		title: 'Risen',
		description: 'Follow a sequenced composition through FM synthesis, an amplitude envelope and reverb.',
		path: 'audio/risen.8f4e',
	},
	{
		id: 'aftertouch',
		title: 'Aftertouch',
		description: 'Explore Amiga MOD playback with four sample channels, pattern sequencing and volume effects.',
		path: 'audio/amigaMods/aftertouch.8f4e',
	},
	{
		id: 'hymn-to-aurora',
		title: 'Hymn to Aurora',
		description: 'Play an Amiga MOD arrangement and inspect its patterns, samples and four channel scopes.',
		path: 'audio/amigaMods/hymn_to_aurora.8f4e',
	},
	{
		id: 'lower-intentions',
		title: 'Lower Intentions',
		description: 'Follow an Amiga MOD track through its timing, sample players and stereo mixer.',
		path: 'audio/amigaMods/lowerIntentions.8f4e',
	},
	{
		id: 'pneumatic',
		title: 'Pneumatic',
		description: 'Inspect an Amiga MOD player with pattern data, tempo controls and four sample voices.',
		path: 'audio/amigaMods/pneumatic.8f4e',
	},
	{
		id: 'midi-input',
		title: 'MIDI input',
		description: 'Inspect the status, channel and data bytes of the latest event from a connected MIDI input.',
		path: 'midi/midiIn.8f4e',
	},
	{
		id: 'xor-network',
		title: 'XOR neural network',
		description: 'Toggle two inputs and see a small pre-trained neural network solve the XOR problem.',
		path: 'machine-learning/xorProblem.8f4e',
	},
	{
		id: 'digit-classifier',
		title: 'Digit classifier',
		description: 'Draw a digit on a 3 × 5 grid and follow its classification through a neural network.',
		path: 'machine-learning/digitClassifier.8f4e',
	},
	{
		id: 'dancing-sine',
		title: 'Dancing with the sine table',
		description: 'Follow four moving pointers as they step through a sine lookup table.',
		path: 'visuals/dancingWithTheSineLT.8f4e',
	},
];

export const projectCategories = [
	{ path: 'misc', title: 'Basics' },
	{ path: 'audio', title: 'Audio' },
	{ path: 'audio/amigaMods', title: 'Amiga MODs' },
	{ path: 'digital', title: 'Digital logic' },
	{ path: 'midi', title: 'MIDI' },
	{ path: 'machine-learning', title: 'Machine learning' },
	{ path: 'visuals', title: 'Visuals' },
].map(category => ({
	...category,
	projects: projects.filter(project => project.path.slice(0, project.path.lastIndexOf('/')) === category.path),
}));
