import { describe, expect, it } from 'vitest';
import highlightSyntax8f4e from './highlightSyntax8f4e';

const spriteLookups = {
	fontLineNumber: 'line',
	fontInstruction: 'instruction',
	fontCode: 'code',
	fontCodeComment: 'comment',
	fontNumbers: 'number',
	fontBinaryZero: 'zero',
	fontBinaryOne: 'one',
	fontBasePrefix: 'prefix',
} as const;

describe('highlightSyntax8f4e', () => {
	it('highlights 8f4e code with instructions, comments, numbers, and binary literals', () => {
		const code8f4e = [
			'module audioout',
			'',
			'float* in &saw.out',
			'int channel LEFT_CHANNEL',
			'',
			'; Audio buffer',
			'float[] buffer AUDIO_BUFFER_SIZE',
			'int pointer &buffer',
			'',
			'; @watch count',
			'; @plot &buffer',
			'push 1 ; @watch counter',
			'',
			'; Store the input value',
			'; in the buffer',
			'push pointer',
			'push *in',
			'store',
			'',
			'; Increment the buffer pointer',
			'; by the buffer element size',
			'push &pointer',
			'push pointer',
			'push %buffer',
			'add',
			'store',
			'',
			'; Reset when reaching end',
			'push pointer',
			'push buffer&',
			'greaterThan',
			'if',
			'  push &pointer',
			'  push &buffer',
			'  store',
			'ifEnd',
			'',
			'; Binary flags',
			'const 0b1010',
			'const 0b1100',
			'and',
			'',
			'; Hex values',
			'push 0xff',
			'push 0x100',
			'mul',
			'',
			'; Conditional logic',
			'push 0',
			'push 10',
			'lessThan',
			'branchIfTrue',
			'',
			'; this is a push comment',
			'; this is a push comment 0b1010',
			'',
			'; Bracketed types',
			'int8[] buffer1 10',
			'int8u[] buffer2 20',
			'int16[] buffer3 30',
			'int16u[] buffer4 40',
			'',
			'; Tab-separated numeric arguments',
			'int foo\t1\t2\t3',
			'push\t123',
			'int\tCONST',
			'',
			'; Numbers inside brackets',
			'push foo[0]',
			'',
			'; Constant names with # digits',
			'const C#7',
			'const GB7',
			'',
			'; Hash comment edge cases',
			'const A#0 22',
			'  # comment',
			'const FOOBAR 42 # comment',
			'',
			'; Float64 instructions',
			'float64**[] OUT',
			'castToFloat64',
			'',
			'moduleEnd',
		];

		const result = highlightSyntax8f4e(code8f4e, spriteLookups);
		expect(result).toMatchSnapshot();
	});
});
