import type { CompilerASTLine, InstructionCompiler, MemoryAddressRange, StackItem } from '@8f4e/language-spec';
import {
	clampAddressByteCode,
	getClampAccessByteWidth,
	getModuleAddressRange,
	rangeUpperByteAddressCode,
} from './utils/addressClamp';
import { linearLastValidStartAddress } from './utils/memoryAccessGuard';
import { saveByteCode } from './utils/saveByteCode';
import { requireStackAddress } from './utils/stackItem';

function clampToRange(
	line: CompilerASTLine,
	context: Parameters<InstructionCompiler>[1],
	operand: StackItem,
	range: MemoryAddressRange
) {
	const accessByteWidth = getClampAccessByteWidth(line);
	return saveByteCode(
		context,
		clampAddressByteCode(context, line, range.byteAddress, rangeUpperByteAddressCode(range, accessByteWidth))
	);
}

/**
 * Clamps the top stack address to its inferred safe or explicit clamp range.
 *
 * @param line - Clamp instruction line with stack-analysis metadata.
 * @param context - Compilation context receiving the generated bytecode.
 * @returns The updated compilation context.
 */
export const clampAddress: InstructionCompiler = (line, context) => {
	const [rawOperand] = line.stackAnalysis.consumedOperands;
	const operand = requireStackAddress(rawOperand, line, context);
	const range = operand.address.clampRange ?? operand.address.safeRange;

	return clampToRange(line, context, operand, range!);
};

/**
 * Clamps the top stack address to the active module's memory range.
 *
 * @param line - Clamp instruction line with stack-analysis metadata.
 * @param context - Compilation context for the active module.
 * @returns The updated compilation context.
 */
export const clampModuleAddress: InstructionCompiler = (line, context) => {
	const [rawOperand] = line.stackAnalysis.consumedOperands;
	const operand = requireStackAddress(rawOperand, line, context);
	return clampToRange(line, context, operand, getModuleAddressRange(context));
};

/**
 * Clamps the top stack address to the whole linear memory range for its access width.
 *
 * @param line - Clamp instruction line with stack-analysis metadata.
 * @param context - Compilation context receiving the generated bytecode.
 * @returns The updated compilation context.
 */
export const clampGlobalAddress: InstructionCompiler = (line, context) => {
	const [rawOperand] = line.stackAnalysis.consumedOperands;
	const operand = requireStackAddress(rawOperand, line, context);
	const accessByteWidth = getClampAccessByteWidth(line);

	return saveByteCode(
		context,
		clampAddressByteCode(context, line, 0, linearLastValidStartAddress(accessByteWidth, operand.address.memoryIndex))
	);
};
