import type { CompilerASTLine, InstructionCompiler, MemoryAddressRange } from '@8f4e/language-spec';
import { clampAddressByteCode, rangeUpperByteAddressCode } from './utils/addressClamp';
import { linearLastValidStartAddress } from './utils/memoryAccessGuard';
import { saveByteCode } from './utils/saveByteCode';

function clampToRange(
	line: CompilerASTLine,
	context: Parameters<InstructionCompiler>[1],
	range: MemoryAddressRange,
	accessByteWidth: number
) {
	return saveByteCode(
		context,
		clampAddressByteCode(context, line, range.byteAddress, rangeUpperByteAddressCode(range, accessByteWidth))
	);
}

/**
 * Clamps the top stack address to its inferred safe or explicit clamp range.
 *
 * @param line - Clamp instruction line with stack-analysis metadata.
 * @param context - Compilation context receiving the generated bytecode.
 * @returns The updated compilation context.
 */
export const clampAddress: InstructionCompiler = (line, context, facts) => {
	const { accessByteWidth, range } = facts.clamp!;

	return clampToRange(line, context, range!, accessByteWidth);
};

/**
 * Clamps the top stack address to the active module's memory range.
 *
 * @param line - Clamp instruction line with stack-analysis metadata.
 * @param context - Compilation context for the active module.
 * @returns The updated compilation context.
 */
export const clampModuleAddress: InstructionCompiler = (line, context, facts) => {
	const { accessByteWidth, range } = facts.clamp!;

	return clampToRange(line, context, range!, accessByteWidth);
};

/**
 * Clamps the top stack address to the whole linear memory range for its access width.
 *
 * @param line - Clamp instruction line with stack-analysis metadata.
 * @param context - Compilation context receiving the generated bytecode.
 * @returns The updated compilation context.
 */
export const clampGlobalAddress: InstructionCompiler = (line, context, facts) => {
	const { accessByteWidth, memoryIndex } = facts.clamp!;

	return saveByteCode(
		context,
		clampAddressByteCode(context, line, 0, linearLastValidStartAddress(accessByteWidth, memoryIndex))
	);
};
