import type { Project } from '@8f4e/editor-state';

const project: Project = {
	codeBlocks: [
		{
			code: ['config', '', 'scope "memorySizeBytes"', 'push 65536', 'set', 'popScope', '', 'configEnd'],
			gridCoordinates: {
				x: -141,
				y: 4,
			},
		},
		{
			code: [
				'config',
				'',
				'scope "runtimeSettings"',
				'',
				'scope "sampleRate"',
				'push 44100',
				'set',
				'',
				'rescopeTop "runtime"',
				'push "AudioWorkletRuntime"',
				'set',
				'',
				'configEnd',
			],
			gridCoordinates: {
				x: -141,
				y: 19,
			},
		},
		{
			code: [
				'config',
				'',
				'rescope "runtimeSettings"',
				'scope "audioOutputBuffers[0]"',
				'',
				'scope "memoryId"',
				'push "audiooutL.buffer"',
				'set',
				'',
				'rescopeTop "channel"',
				'push 0',
				'set',
				'',
				'rescopeTop "output"',
				'push 0',
				'set',
				'',
				'rescope "runtimeSettings"',
				'scope "audioOutputBuffers[1]"',
				'',
				'scope "memoryId"',
				'push "audiooutR.buffer"',
				'set',
				'',
				'rescopeTop "channel"',
				'push 1',
				'set',
				'',
				'rescopeTop "output"',
				'push 0',
				'set',
				'',
				'configEnd',
			],
			gridCoordinates: {
				x: -106,
				y: 13,
			},
		},
		{
			code: [
				'config',
				'',
				'rescope "runtimeSettings"',
				'scope "audioInputBuffers[0]"',
				'',
				'scope "memoryId"',
				'push "audioin.buffer"',
				'set',
				'',
				'rescopeTop "channel"',
				'push 0',
				'set',
				'',
				'rescopeTop "input"',
				'push 0',
				'set',
				'',
				'configEnd',
			],
			gridCoordinates: {
				x: -106,
				y: -10,
			},
		},
		{
			code: [
				'module audioin',
				'use env',
				'',
				'; Audio buffer',
				'float[] buffer AUDIO_BUFFER_SIZE',
				'float out',
				'int pointer &buffer',
				'',
				'plot buffer -2 2',
				'',
				'push &out',
				'push pointer',
				'loadFloat',
				'store',
				'',
				'push &pointer ',
				'push pointer',
				'push WORD_SIZE',
				'add',
				'store',
				'',
				'push pointer',
				'push buffer&',
				'greaterThan',
				'if void',
				' push &pointer',
				' push &buffer',
				' store',
				'ifEnd',
				'',
				'moduleEnd',
			],
			gridCoordinates: {
				x: 5,
				y: 1,
			},
		},
		{
			code: [
				'module audiooutL',
				'use env',
				'',
				'float* in &audioin.out',
				'',
				'; Audio buffer',
				'float[] buffer AUDIO_BUFFER_SIZE',
				'int pointer &buffer',
				'',
				'plot buffer -2 2',
				'',
				'; Store the input value',
				'; in the buffer',
				'push pointer',
				'push *in',
				'store',
				'',
				'; Increment the buffer ',
				'; pointer by the word size',
				'; which is 4 bytes',
				'push &pointer',
				'push pointer',
				'push WORD_SIZE',
				'add',
				'store',
				'',
				'; Reset the buffer pointer',
				'; when it reaches the end',
				'; of the buffer',
				'push pointer',
				'push buffer&',
				'greaterThan',
				'if void',
				' push &pointer',
				' push &buffer',
				' store',
				'ifEnd',
				'',
				'moduleEnd',
			],
			gridCoordinates: {
				x: 48,
				y: 1,
			},
		},
		{
			code: [
				'module audiooutR',
				'use env',
				'',
				'float* in &audioin.out',
				'',
				'; Audio buffer',
				'float[] buffer AUDIO_BUFFER_SIZE',
				'int pointer &buffer',
				'',
				'plot buffer -2 2',
				'',
				'; Store the input value',
				'; in the buffer',
				'push pointer',
				'push *in',
				'store',
				'',
				'; Increment the buffer ',
				'; pointer by the word size',
				'; which is 4 bytes',
				'push &pointer',
				'push pointer',
				'push WORD_SIZE',
				'add',
				'store',
				'',
				'; Reset the buffer pointer',
				'; when it reaches the end',
				'; of the buffer',
				'push pointer',
				'push buffer&',
				'greaterThan',
				'if void',
				' push &pointer',
				' push &buffer',
				' store',
				'ifEnd',
				'',
				'moduleEnd',
			],
			gridCoordinates: {
				x: 89,
				y: 1,
			},
		},
		{
			code: [
				'constants env',
				'; Auto-generated environment constants',
				'; Changes will be overwritten',
				'; Last updated: 1/19/2026, 9:50:35 PM',
				'',
				'const WORD_SIZE 4',
				'',
				'const SAMPLE_RATE 44100',
				'const AUDIO_BUFFER_SIZE 128',
				'',
				'constantsEnd',
			],
			gridCoordinates: {
				x: -52,
				y: 1,
			},
		},
	],
	viewport: {
		gridCoordinates: {
			x: 3,
			y: 0,
		},
	},
};

export default project;
