import type { Project } from '@8f4e/editor-state';

const project: Project = {
	codeBlocks: [
		{
			code: [
				'config',
				'',
				'scope "projectInfo"',
				'scope "title"',
				'push "Audio Loopback"',
				'set',
				'rescopeTop "author"',
				'push "Andor Polgar"',
				'set',
				'rescopeTop "description"',
				'push ""',
				'set',
				'popScope',
				'',
				'scope "memorySizeBytes"',
				'push 65536',
				'set',
				'popScope',
				'',
				'scope "selectedRuntime"',
				'push 0',
				'set',
				'popScope',
				'',
				'scope "runtimeSettings"',
				'scope 0',
				'scope "sampleRate"',
				'push 44100',
				'set',
				'rescopeTop "runtime"',
				'push "AudioWorkletRuntime"',
				'set',
				'rescopeTop "audioOutputBuffers"',
				'scope 0',
				'scope "moduleId"',
				'push "audiooutL"',
				'set',
				'rescopeTop "memoryId"',
				'push "buffer"',
				'set',
				'rescopeTop "channel"',
				'push 0',
				'set',
				'rescopeTop "output"',
				'push 0',
				'set',
				'popScope',
				'scope 1',
				'scope "moduleId"',
				'push "audiooutR"',
				'set',
				'rescopeTop "memoryId"',
				'push "buffer"',
				'set',
				'rescopeTop "channel"',
				'push 1',
				'set',
				'rescopeTop "output"',
				'push 0',
				'set',
				'popScope',
				'popScope',
				'rescopeTop "audioInputBuffers"',
				'scope 0',
				'scope "moduleId"',
				'push "audioin"',
				'set',
				'rescopeTop "memoryId"',
				'push "buffer"',
				'set',
				'rescopeTop "channel"',
				'push 0',
				'set',
				'rescopeTop "input"',
				'push 0',
				'set',
				'popScope',
				'popScope',
				'popScope',
				'popScope',
				'',
				'configEnd',
			],
			gridCoordinates: { x: -30, y: 3 },
		},
		{
			code: [
				'module audioin',
				'',
				'; Audio buffer',
				'float[] buffer AUDIO_BUFFER_SIZE',
				'float out',
				'int pointer &buffer',
				'',
				'debug out',
				'',
				'plot buffer -2 2',
				'',
				'push &out',
				'push pointer',
				'loadFloat',
				'store',
				'',
				'push &pointer ',
				'push pointer',
				'push WORD_SIZE',
				'add',
				'store',
				'',
				'push pointer',
				'push buffer&',
				'greaterThan',
				'if void',
				' push &pointer',
				' push &buffer',
				' store',
				'ifEnd',
				'',
				'moduleEnd',
			],
			gridCoordinates: { x: 6, y: 3 },
		},
		{
			code: [
				'module audiooutL',
				'',
				'float* in &audioin.out',
				'',
				'; Audio buffer',
				'float[] buffer AUDIO_BUFFER_SIZE',
				'int pointer &buffer',
				'',
				'plot buffer -2 2',
				'',
				'; Store the input value',
				'; in the buffer',
				'push pointer',
				'push *in',
				'store',
				'',
				'; Increment the buffer ',
				'; pointer by the word size',
				'; which is 4 bytes',
				'push &pointer',
				'push pointer',
				'push WORD_SIZE',
				'add',
				'store',
				'',
				'; Reset the buffer pointer',
				'; when it reaches the end',
				'; of the buffer',
				'push pointer',
				'push buffer&',
				'greaterThan',
				'if void',
				' push &pointer',
				' push &buffer',
				' store',
				'ifEnd',
				'',
				'moduleEnd',
			],
			gridCoordinates: { x: 48, y: 1 },
		},
		{
			code: [
				'module audiooutR',
				'',
				'float* in &audioin.out',
				'',
				'; Audio buffer',
				'float[] buffer AUDIO_BUFFER_SIZE',
				'int pointer &buffer',
				'',
				'plot buffer -2 2',
				'',
				'; Store the input value',
				'; in the buffer',
				'push pointer',
				'push *in',
				'store',
				'',
				'; Increment the buffer ',
				'; pointer by the word size',
				'; which is 4 bytes',
				'push &pointer',
				'push pointer',
				'push WORD_SIZE',
				'add',
				'store',
				'',
				'; Reset the buffer pointer',
				'; when it reaches the end',
				'; of the buffer',
				'push pointer',
				'push buffer&',
				'greaterThan',
				'if void',
				' push &pointer',
				' push &buffer',
				' store',
				'ifEnd',
				'',
				'moduleEnd',
			],
			gridCoordinates: { x: 90, y: 1 },
		},
	],
	viewport: { gridCoordinates: { x: -17, y: -3 } },
};

export default project;
