import type { Project } from '@8f4e/editor-state';

const project: Project = {
	memorySizeBytes: 65536,
	title: '',
	author: '',
	description: '',
	codeBlocks: [
		{
			code: [
				'config',
				'',
				'scope "projectInfo"',
				'  scope "title"',
				'    push "Audio Buffer"',
				'    set',
				'  popScope',
				'  scope "author"',
				'    push "Andor Polgar"',
				'    set',
				'  popScope',
				'popScope',
				'',
				'scope "memorySizeBytes"',
				'  push 65536',
				'  set',
				'popScope',
				'',
				'configEnd',
			],
			gridCoordinates: { x: -30, y: 1 },
		},
		{
			code: [
				'module saw',
				'',
				'debug out',
				'',
				'float out',
				'',
				'; Increment the value by 1',
				'push &out',
				'push out',
				'push 0.02032',
				'add',
				'store',
				'',
				'; Reset the value to -100',
				'; when it reaches 100',
				'push out',
				'push 1.0',
				'greaterThan',
				'if void',
				' push &out',
				' push -1.0',
				' store',
				'ifEnd',
				'moduleEnd',
			],
			gridCoordinates: { x: 2, y: 1 },
		},
		{
			code: [
				'module audioout',
				'',
				'float* in &saw.out',
				'int channel LEFT_CHANNEL',
				'',
				'; Audio buffer',
				'float[] buffer AUDIO_BUFFER_SIZE',
				'int pointer &buffer',
				'',
				'plot buffer -2 2',
				'',
				'; Store the input value',
				'; in the buffer',
				'push pointer',
				'push *in',
				'store',
				'',
				'; Increment the buffer ',
				'; pointer by the word size',
				'; which is 4 bytes',
				'push &pointer',
				'push pointer',
				'push WORD_SIZE',
				'add',
				'store',
				'',
				'; Reset the buffer pointer',
				'; when it reaches the end',
				'; of the buffer',
				'push pointer',
				'push buffer&',
				'greaterThan',
				'if void',
				' push &pointer',
				' push &buffer',
				' store',
				'ifEnd',
				'',
				'moduleEnd',
			],
			gridCoordinates: { x: 37, y: 1 },
		},
	],
	viewport: { gridCoordinates: { x: 0, y: 0 } },
	selectedRuntime: 0,
	runtimeSettings: [
		{
			sampleRate: 44100,
			runtime: 'AudioWorkletRuntime',
			audioOutputBuffers: [{ moduleId: 'audioout', memoryId: 'buffer', channel: 0, output: 0 }],
		},
	],
};

export default project;
