import type { Project } from '@8f4e/editor-state';

const project: Project = {
	codeBlocks: [
		{
			code: [
				'config',
				'',
				'rescope "memorySizeBytes"',
				'push 65536',
				'set',
				'',

				'rescope "runtimeSettings"',
				'',
				'scope "sampleRate"',
				'push 50',
				'set',
				'',
				'rescopeTop "runtime"',
				'push "WebWorkerLogicRuntime"',
				'set',
				'',
				'configEnd',
			],
			gridCoordinates: {
				x: -67,
				y: 16,
			},
		},
		{
			code: [
				'module andGate',
				'',
				'         ;   .---.',
				"int* in1 ; --+    '   ",
				'int out  ;   | AND |---',
				'int* in2 ; --+    .',
				"         ;   '---'",
				'',
				'init in1 &orGate.out',
				'init in2 &negate.out',
				'push &out',
				'push *in1',
				'push *in2',
				'mul',
				'push 1',
				'greaterOrEqual',
				'if ',
				'push 1',
				'else',
				'push 0',
				'ifEnd',
				'store',
				'',
				'moduleEnd',
			],
			gridCoordinates: {
				x: 243,
				y: 31,
			},
		},
		{
			code: [
				'module buttons',
				'',
				'; Buttons for the SR AND-OR latch',
				'',
				'int set',
				'int reset',
				'               ; Push this button',
				'               ; to set the state',
				'button set 0 1 ; of the latch  -->  ',
				'',
				'                 ; Push this button',
				'button reset 0 1 ; to reset   --->',
				'',
				'moduleEnd',
			],
			gridCoordinates: {
				x: 196,
				y: 16,
			},
		},
		{
			code: [
				'module comment',
				'',
				'; Of course there is an easier',
				'; way to implement latching',
				'; logic in 8F4E, this is just',
				'; a fun project to demonstrate',
				'; feedback between modules.',
				'',
				'',
				'moduleEnd',
			],
			gridCoordinates: {
				x: 131,
				y: 14,
			},
		},
		{
			code: [
				'constants env',
				'; Auto-generated environment constants',
				'; Changes will be overwritten',
				'; Last updated: 1/19/2026, 9:52:44 PM',
				'',
				'const WORD_SIZE 4',
				'',
				'const SAMPLE_RATE 50',
				'const AUDIO_BUFFER_SIZE 128',
				'',
				'constantsEnd',
			],
			gridCoordinates: {
				x: -30,
				y: 16,
			},
		},
		{
			code: [
				'module negate',
				'',
				'int* in &buttons.reset',
				'int out',
				'',
				'push &out',
				'push *in',
				'push 0',
				'equal',
				'if ',
				'push 1',
				'else',
				'push 0',
				'ifEnd',
				'store',
				'',
				'moduleEnd',
			],
			gridCoordinates: {
				x: 207,
				y: 33,
			},
		},
		{
			code: [
				'module norGate',
				'',
				'         ;   .---.',
				"int* in1 ; --+    '",
				'int out  ;   ) NOR |O--- ',
				'int* in2 ; --+    .',
				"         ;   '---'",
				'debug out',
				'',
				'init in1 &norGate2.out',
				'init in2 &resetButton.out',
				'',
				'push &out',
				'push *in1',
				'push *in2',
				'add',
				'push 0',
				'equal',
				'if ',
				'push 1',
				'else',
				'push 0',
				'ifEnd',
				'store',
				'',
				'moduleEnd',
			],
			gridCoordinates: {
				x: 95,
				y: 35,
			},
		},
		{
			code: [
				'module norGate2',
				'',
				'         ;   .---.',
				"int* in1 ; --+    '   ",
				'int out  ;   ) NOR |O--- ',
				'int* in2 ; --+    .',
				"         ;   '---'",
				'',
				'debug out',
				'',
				'init in1 &norGate.out',
				'init in2 &setButton.out',
				'push &out',
				'push *in1',
				'push *in2',
				'add',
				'push 0',
				'equal',
				'if ',
				'push 1 ',
				'else',
				'push 0',
				'ifEnd',
				'store',
				'',
				'moduleEnd',
			],
			gridCoordinates: {
				x: 95,
				y: 8,
			},
		},
		{
			code: [
				'module orGate',
				'',
				'         ;   .---.',
				"int* in1 ; --+    '   ",
				'int out  ;   ) OR  |---',
				'int* in2 ; --+    .',
				"         ;   '---'",
				'',
				'init in1 &andGate.out',
				'init in2 &buttons.set',
				'push &out',
				'push *in1',
				'push *in2',
				'add',
				'push 1',
				'greaterOrEqual',
				'if ',
				'push 1',
				'else',
				'push 0',
				'ifEnd',
				'store',
				'',
				'moduleEnd',
			],
			gridCoordinates: {
				x: 243,
				y: 6,
			},
		},
		{
			code: [
				'module resetButton',
				'',
				'int out',
				'               ; Push this button',
				'               ; to reset the state',
				'button out 0 1 ; of the SR latch -->  ',
				'',
				'moduleEnd',
			],
			gridCoordinates: {
				x: 47,
				y: 27,
			},
		},
		{
			code: [
				'module scope',
				'use env',
				'',
				'int* in &norGate.out',
				'int[] buffer 64',
				'int bufferPointer &buffer',
				'',
				'plot buffer -1 2',
				'',
				'push &bufferPointer',
				'push bufferPointer',
				'push WORD_SIZE',
				'add',
				'store',
				'',
				'push bufferPointer',
				'push buffer&',
				'greaterThan',
				'if void',
				' push &bufferPointer',
				' push &buffer',
				' store',
				'ifEnd',
				'',
				'push bufferPointer',
				'push *in',
				'store',
				'',
				'moduleEnd',
			],
			gridCoordinates: {
				x: 131,
				y: 26,
			},
		},
		{
			code: [
				'module scope2',
				'use env',
				'',
				'int* in &andGate.out',
				'int[] buffer 64',
				'int bufferPointer &buffer',
				'',
				'plot buffer -1 2',
				'',
				'push &bufferPointer',
				'push bufferPointer',
				'push WORD_SIZE',
				'add',
				'store',
				'',
				'push bufferPointer',
				'push buffer&',
				'greaterThan',
				'if void',
				'push &bufferPointer',
				'push &buffer',
				'store',
				'ifEnd',
				'',
				'push bufferPointer',
				'push *in',
				'store',
				'',
				'moduleEnd',
			],
			gridCoordinates: {
				x: 279,
				y: 19,
			},
		},
		{
			code: [
				'module setButton',
				'',
				'int out',
				'               ; Push this button',
				'               ; to set the state',
				'button out 0 1 ; of the SR latch -->  ',
				'',
				'moduleEnd',
			],
			gridCoordinates: {
				x: 47,
				y: 17,
			},
		},
	],
	viewport: {
		gridCoordinates: {
			x: 45,
			y: 7,
		},
	},
};

export default project;
