import type { Project } from '@8f4e/editor-state';

const project: Project = {
	codeBlocks: [
		{
			code: [
				'fragmentShader motionBlurTrail',
				'#version 300 es',
				'precision mediump float;',
				'',
				'#define BLUR_SAMPLES 8',
				'#define BLUR_SCALE 0.01',
				'#define BLUR_SPEED 0.6',
				'',
				'in vec2 v_screenCoord;',
				'uniform float u_time;',
				'uniform sampler2D u_renderTexture;',
				'out vec4 outColor;',
				'',
				'void main() {',
				'  vec2 uv = v_screenCoord;',
				'  vec2 direction = vec2(cos(u_time * BLUR_SPEED), sin(u_time * BLUR_SPEED));',
				'',
				'  vec3 color = vec3(0.0);',
				'  float weightSum = 0.0;',
				'',
				'  for (int i = 0; i < BLUR_SAMPLES; i++) {',
				'    float t = float(i) / float(BLUR_SAMPLES - 1);',
				'    float weight = mix(1.0, 0.15, t);',
				'    vec2 offset = direction * BLUR_SCALE * t;',
				'    color += texture(u_renderTexture, uv - offset).rgb * weight;',
				'    weightSum += weight;',
				'  }',
				'',
				'  color /= max(weightSum, 0.0001);',
				'  outColor = vec4(color, 1.0);',
				'}',
				'fragmentShaderEnd',
			],
			gridCoordinates: {
				x: 87,
				y: 10,
			},
		},
		{
			code: [
				'config',
				'',
				'scope "memorySizeBytes"',
				'push 65536',
				'set',
				'popScope',
				'',
				'scope "selectedRuntime"',
				'push 0',
				'set',
				'popScope',
				'',
				'scope "runtimeSettings[0]"',
				'scope "runtime"',
				'push "WebWorkerLogicRuntime"',
				'set',
				'rescopeTop "sampleRate"',
				'push 50',
				'set',
				'popScope',
				'popScope',
				'',
				'configEnd',
			],
			gridCoordinates: {
				x: -15,
				y: 11,
			},
		},
		{
			code: [
				'module main',
				'',
				'; This project simulates a motion trail',
				'; by sampling the current frame along a',
				'; rotating blur direction.',
				'',
				'moduleEnd',
			],
			gridCoordinates: {
				x: 28,
				y: 12,
			},
		},
	],
	viewport: {
		gridCoordinates: {
			x: -46,
			y: -5,
		},
	},
	binaryAssets: [],
};

export default project;
