import type { Project } from '@8f4e/editor-state';

const project: Project = {
	codeBlocks: [
		{
			code: [
				'config',
				'',
				'scope "title"',
				'push "Neural Network"',
				'set',
				'rescopeTop "author"',
				'push "Andor Polgar"',
				'set',
				'rescopeTop "description"',
				'push "A simple neural network pre-trained as an XOR gate."',
				'set',
				'popScope',
				'',
				'scope "memorySizeBytes"',
				'push 65536',
				'set',
				'popScope',
				'',
				'scope "selectedRuntime"',
				'push 0',
				'set',
				'popScope',
				'',
				'scope "runtimeSettings"',
				'scope 0',
				'scope "sampleRate"',
				'push 50',
				'set',
				'rescopeTop "runtime"',
				'push "WebWorkerLogicRuntime"',
				'set',
				'popScope',
				'popScope',
				'',
				'configEnd',
			],
			gridCoordinates: { x: 40, y: -81 },
		},
		{
			code: [
				'module activationFunction',
				'',
				'float* in &sigmoid3.out',
				'int out',
				'',
				'push &out',
				'push *in',
				'',
				'push 0.5',
				'greaterThan',
				'if int',
				' push 1',
				'else',
				' push 0',
				'ifEnd',
				'store',
				'',
				'moduleEnd',
			],
			gridCoordinates: { x: 262, y: -71 },
		},
		{
			code: [
				'module perceptron',
				'; Pre-trained perceptron',
				'',
				'float* in1 &switches.out1',
				'float* in2 &switches.out2',
				'float out',
				'',
				'; Training data',
				'const w1 10.056234',
				'const w2 -42.53689',
				'const bias -3.92453',
				'',
				'push &out',
				'push *in1',
				'push w1',
				'mul',
				'push *in2',
				'push w2',
				'mul',
				'add',
				'push bias',
				'add',
				'store',
				'moduleEnd',
			],
			gridCoordinates: { x: 118, y: -81 },
		},
		{
			code: [
				'module perceptron2',
				'; Pre-trained perceptron',
				'',
				'float* in1 &switches.out1',
				'float* in2 &switches.out2',
				'float out',
				'',
				'; Training data',
				'const w1 -70.313797',
				'const w2 24.76387',
				'const bias -8.765101',
				'',
				'push &out',
				'push *in1',
				'push w1',
				'mul',
				'push *in2',
				'push w2',
				'mul',
				'add',
				'push bias',
				'add',
				'store',
				'moduleEnd',
			],
			gridCoordinates: { x: 118, y: -55 },
		},
		{
			code: [
				'module perceptron3',
				'; Pre-trained perceptron',
				'',
				'float* in1 &sigmoid.out',
				'float* in2 &sigmoid2.out',
				'float out ',
				'',
				'; Training data',
				'const w1 6.94625',
				'const w2 6.64608',
				'const bias 6.05782',
				'',
				'push &out',
				'push *in1',
				'push w1',
				'mul',
				'push *in2',
				'push w2',
				'mul',
				'add',
				'push bias',
				'add',
				'store',
				'moduleEnd',
			],
			gridCoordinates: { x: 190, y: -71 },
		},
		{
			code: ['module result', '', 'int* in &activationFunction.out', '', 'debug *in', '', 'moduleEnd'],
			gridCoordinates: { x: 76, y: -61 },
		},
		{
			code: [
				'module sigmoid',
				'; Polynomial sigmoid ',
				'; funtion approximation',
				'',
				'float* in &perceptron.out',
				'float out',
				'',
				'push &out',
				'push *in',
				'push *in',
				'abs',
				'push 1.0',
				'add',
				'ensureNonZero',
				'div',
				'store',
				'',
				'moduleEnd',
			],
			gridCoordinates: { x: 154, y: -81 },
		},
		{
			code: [
				'module sigmoid2',
				'; Polynomial sigmoid ',
				'; funtion approximation',
				'',
				'float* in &perceptron2.out',
				'float out',
				'',
				'push &out',
				'push *in',
				'push *in',
				'abs',
				'push 1.0',
				'add',
				'ensureNonZero',
				'div',
				'store',
				'',
				'moduleEnd',
			],
			gridCoordinates: { x: 154, y: -55 },
		},
		{
			code: [
				'module sigmoid3',
				'; Polynomial sigmoid ',
				'; funtion approximation',
				'',
				'float* in &perceptron3.out',
				'float out',
				'',
				'push &out',
				'push *in',
				'push *in',
				'abs',
				'push 1.0',
				'add',
				'ensureNonZero',
				'div',
				'store',
				'',
				'moduleEnd',
			],
			gridCoordinates: { x: 226, y: -71 },
		},
		{
			code: ['module switches', '', 'float out1 1.0', 'float out2 0.0', '', 'moduleEnd'],
			gridCoordinates: { x: 81, y: -68 },
		},
	],
	viewport: { gridCoordinates: { x: 73, y: -83 } },
};

export default project;
