import type { Project } from '@8f4e/editor-state';

const project: Project = {
	codeBlocks: [
		{
			code: [
				'config',
				'',
				'scope "projectInfo"',
				'scope "title"',
				'push "Random Generators"',
				'set',
				'rescopeTop "author"',
				'push "Andor Polgar"',
				'set',
				'rescopeTop "description"',
				'push ""',
				'set',
				'popScope',
				'',
				'scope "memorySizeBytes"',
				'push 65536',
				'set',
				'popScope',
				'',
				'scope "selectedRuntime"',
				'push 0',
				'set',
				'popScope',
				'',
				'scope "runtimeSettings"',
				'scope 0',
				'scope "runtime"',
				'push "WebWorkerLogicRuntime"',
				'set',
				'rescopeTop "sampleRate"',
				'push 50',
				'set',
				'popScope',
				'popScope',
				'',
				'configEnd',
			],
			gridCoordinates: { x: -35, y: 1 },
		},
		{
			code: [
				'module lcg',
				'; Linear congruential ',
				'; generator',
				'',
				'const multiplier 1664525',
				'const increment 1013904223 ',
				'const modulus 65536 ; 2^16',
				'int seed 69420',
				'',
				'float out',
				'',
				'push &seed',
				' push multiplier',
				' push seed',
				' mul',
				' push increment',
				' add',
				' push modulus',
				' remainder',
				'store',
				'',
				'push &out',
				' push seed',
				' castToFloat',
				' push modulus',
				' castToFloat',
				' div ',
				'store',
				'',
				'moduleEnd',
			],
			gridCoordinates: { x: 2, y: 1 },
		},
		{
			code: [
				'module XORShift',
				'',
				'int seed 69420',
				'float out',
				'',
				'push &seed',
				' push seed',
				' push seed',
				' push 13',
				' shiftLeft',
				' xor',
				'',
				' push seed',
				' push 17',
				' shiftRight',
				' xor',
				'',
				' push seed',
				' push 5',
				' shiftLeft',
				' xor',
				'store',
				'',
				'push &out',
				' push seed',
				' castToFloat',
				' push 2147483647',
				' castToFloat',
				' div',
				'store',
				'',
				'moduleEnd',
			],
			gridCoordinates: { x: 74, y: 1 },
		},
		{
			code: [
				'module scope',
				'',
				'float* in &lcg.out',
				'float[] buffer 64',
				'int bufferPointer &buffer',
				'',
				'plot buffer -2 2',
				'',
				'push &bufferPointer',
				'push bufferPointer',
				'push WORD_SIZE',
				'add',
				'store',
				'',
				'push bufferPointer',
				'push buffer&',
				'greaterThan',
				'if void',
				' push &bufferPointer',
				' push &buffer',
				' store',
				'ifEnd',
				'',
				'push bufferPointer',
				'push *in',
				'store',
				'',
				'moduleEnd',
			],
			gridCoordinates: { x: 39, y: 1 },
		},
		{
			code: [
				'module scope2',
				'',
				'float* in &XORShift.out',
				'float[] buffer 64',
				'int bufferPointer &buffer',
				'',
				'plot buffer -2 2',
				'',
				'push &bufferPointer',
				'push bufferPointer',
				'push WORD_SIZE',
				'add',
				'store',
				'',
				'push bufferPointer',
				'push buffer&',
				'greaterThan',
				'if void',
				' push &bufferPointer',
				' push &buffer',
				' store',
				'ifEnd',
				'',
				'push bufferPointer',
				'push *in',
				'store',
				'',
				'moduleEnd',
			],
			gridCoordinates: { x: 109, y: 1 },
		},
	],
	viewport: { gridCoordinates: { x: 0, y: 0 } },
};

export default project;
