import type { Project } from '@8f4e/editor-state';

const project: Project = {
	codeBlocks: [
		{
			code: [
				'config',
				'',
				'scope "memorySizeBytes"',
				'push 65536',
				'set',
				'popScope',
				'',
				'scope "runtimeSettings"',
				'scope "runtime"',
				'push "WebWorkerLogicRuntime"',
				'set',
				'rescopeTop "sampleRate"',
				'push 50',
				'set',
				'popScope',
				'popScope',
				'',
				'configEnd',
			],
			gridCoordinates: {
				x: -59,
				y: 12,
			},
		},
		{
			code: [
				'module counter',
				'',
				'int count',
				'debug count',
				'',
				'push &count',
				'push count',
				'push 1',
				'add',
				'store',
				'',
				'moduleEnd',
			],
			gridCoordinates: {
				x: 25,
				y: 19,
			},
		},
		{
			code: [
				'constants env',
				'; Auto-generated environment constants',
				'; Changes will be overwritten',
				'; Last updated: 1/19/2026, 10:03:27 PM',
				'',
				'const WORD_SIZE 4',
				'',
				'const SAMPLE_RATE 50',
				'const AUDIO_BUFFER_SIZE 128',
				'',
				'constantsEnd',
			],
			gridCoordinates: {
				x: -59,
				y: 0,
			},
		},
		{
			code: [
				'module main',
				'',
				'; This project demonstrates a radial ripple',
				'; post-process effect using GLSL shader',
				'; code blocks.',
				'',
				'moduleEnd',
			],
			gridCoordinates: {
				x: 25,
				y: 10,
			},
		},
		{
			code: [
				'fragmentShader ripple',
				'#version 300 es',
				'',
				'precision mediump float;',
				'',
				'#define RIPPLE_SPEED 5.0',
				'#define RIPPLE_FREQUENCY 50.0',
				'#define RIPPLE_AMPLITUDE 0.0025',
				'#define RIPPLE_FADE 3.0',
				'',
				'in vec2 v_screenCoord;',
				'uniform vec2 u_resolution;',
				'uniform float u_time;',
				'uniform sampler2D u_renderTexture;',
				'out vec4 outColor;',
				'',
				'void main() {',
				'  vec2 uv = v_screenCoord;',
				'',
				'  vec2 center = vec2(0.5, 0.5);',
				'  vec2 offset = uv - center;',
				'  float dist = length(offset);',
				'  float safeDist = max(dist, 0.0001);',
				'',
				'  float wave = sin(dist * RIPPLE_FREQUENCY - u_time * RIPPLE_SPEED);',
				'  float attenuation = exp(-dist * RIPPLE_FADE);',
				'  float displacement = wave * RIPPLE_AMPLITUDE * attenuation;',
				'',
				'  vec2 rippleUV = uv + (offset / safeDist) * displacement;',
				'',
				'  vec3 color = texture(u_renderTexture, rippleUV).rgb;',
				'',
				'  outColor = vec4(color, 1.0);',
				'}',
				'fragmentShaderEnd',
			],
			gridCoordinates: {
				x: 87,
				y: 10,
			},
		},
	],
	viewport: {
		gridCoordinates: {
			x: 21,
			y: 8,
		},
	},
};

export default project;
