import type { Project } from '@8f4e/editor-state';

const project: Project = {
	codeBlocks: [
		{
			code: [
				'fragmentShader ripple',
				'precision mediump float;',
				'',
				'#define RIPPLE_SPEED 2.5',
				'#define RIPPLE_FREQUENCY 16.0',
				'#define RIPPLE_AMPLITUDE 0.02',
				'#define RIPPLE_FADE 3.0',
				'',
				'varying vec2 v_screenCoord;',
				'uniform vec2 u_resolution;',
				'uniform float u_time;',
				'uniform sampler2D u_renderTexture;',
				'',
				'void main() {',
				'  vec2 uv = v_screenCoord;',
				'',
				'  vec2 center = vec2(0.5, 0.5);',
				'  vec2 offset = uv - center;',
				'  float dist = length(offset);',
				'  float safeDist = max(dist, 0.0001);',
				'',
				'  float wave = sin(dist * RIPPLE_FREQUENCY - u_time * RIPPLE_SPEED);',
				'  float attenuation = exp(-dist * RIPPLE_FADE);',
				'  float displacement = wave * RIPPLE_AMPLITUDE * attenuation;',
				'',
				'  vec2 rippleUV = uv + (offset / safeDist) * displacement;',
				'',
				'  vec3 color = texture2D(u_renderTexture, rippleUV).rgb;',
				'',
				'  gl_FragColor = vec4(color, 1.0);',
				'}',
				'fragmentShaderEnd',
			],
			gridCoordinates: {
				x: 87,
				y: 10,
			},
		},
		{
			code: [
				'vertexShader ripple',
				'precision mediump float;',
				'',
				'attribute vec2 a_position;',
				'',
				'varying vec2 v_screenCoord;',
				'',
				'void main() {',
				'  gl_Position = vec4(a_position, 0, 1);',
				'  v_screenCoord = (a_position + 1.0) / 2.0;',
				'}',
				'vertexShaderEnd',
			],
			gridCoordinates: {
				x: 87,
				y: 51,
			},
		},
		{
			code: [
				'config',
				'',
				'scope "memorySizeBytes"',
				'push 65536',
				'set',
				'popScope',
				'',
				'scope "selectedRuntime"',
				'push 0',
				'set',
				'popScope',
				'',
				'scope "runtimeSettings[0]"',
				'scope "runtime"',
				'push "WebWorkerLogicRuntime"',
				'set',
				'rescopeTop "sampleRate"',
				'push 50',
				'set',
				'popScope',
				'popScope',
				'',
				'configEnd',
			],
			gridCoordinates: {
				x: -15,
				y: 11,
			},
		},
		{
			code: [
				'module counter',
				'',
				'int count',
				'debug count',
				'',
				'push &count',
				'push count',
				'push 1',
				'add',
				'store',
				'',
				'moduleEnd',
			],
			gridCoordinates: {
				x: 37,
				y: 27,
			},
		},
		{
			code: [
				'module main',
				'',
				'; This project demonstrates a radial ripple',
				'; post-process effect using GLSL shader',
				'; code blocks.',
				'',
				'moduleEnd',
			],
			gridCoordinates: {
				x: 28,
				y: 12,
			},
		},
	],
	viewport: {
		gridCoordinates: {
			x: -46,
			y: -5,
		},
	},
	binaryAssets: [],
};

export default project;
