import type { Project } from '@8f4e/editor-state';

const project: Project = {
	codeBlocks: [
		{
			code: [
				'projectConfig',
				'',
				'rescope "binaryAssets[]"',
				'',
				'const PROTOCOL "https://"',
				'const DOMAIN "llllllllllll.com"',
				'const SUBDOMAIN "static"',
				'const PATH "/andor/8f4e/"',
				'const SAMPLE "amen"',
				'const BPM "170bpm"',
				'const RES "8bit"',
				'const SIGNEDNESS "unsigned"',
				'const EXT ".pcm"',
				'',
				'scope "url"',
				'push PROTOCOL',
				'push SUBDOMAIN',
				'push "."',
				'push DOMAIN',
				'push PATH',
				'push SAMPLE',
				'push "_"',
				'push BPM',
				'push "_"',
				'push RES',
				'push "_"',
				'push SIGNEDNESS',
				'push EXT',
				'concat',
				'set',
				'',
				'rescopeTop "memoryId"',
				'push "pcmPlayer8bit.buffer"',
				'set',
				'',
				'projectConfigEnd',
			],
			gridCoordinates: {
				x: -9,
				y: -63,
			},
		},
		{
			code: [
				'projectConfig',
				'',
				'rescope "memorySizeBytes"',
				'push 655360',
				'set',
				'popScope',
				'',
				'scope "runtimeSettings"',
				'scope "sampleRate"',
				'push 44100',
				'; push 22050',
				'set',
				'',
				'rescopeTop "runtime"',
				'push "AudioWorkletRuntime"',
				'set',
				'',
				'rescopeTop "audioOutputBuffers[0]"',
				'',
				'scope "memoryId"',
				'push "audioout.buffer"',
				'set',
				'',
				'rescopeTop "channel"',
				'push 0',
				'set',
				'',
				'rescopeTop "output"',
				'push 0',
				'set',
				'',
				'rescope "runtimeSettings"',
				'scope "audioOutputBuffers[1]"',
				'',
				'scope "memoryId"',
				'push "audioout.buffer"',
				'set',
				'',
				'rescopeTop "channel"',
				'push 1',
				'set',
				'',
				'rescopeTop "output"',
				'push 0',
				'set',
				'',
				'popScope',
				'popScope',
				'popScope',
				'popScope',
				'',
				'projectConfigEnd',
			],
			gridCoordinates: {
				x: -53,
				y: -63,
			},
		},
		{
			code: [
				'module audioout',
				'use env',
				'',
				'float* in &pcmPlayer8bit.out',
				'',
				'float[] buffer AUDIO_BUFFER_SIZE',
				'int pointer &buffer',
				'',
				'# plot buffer -1 1',
				'',
				'; Store the input value',
				'; in the buffer',
				'push pointer',
				'push *in',
				'store',
				'',
				'; Increment the buffer ',
				'; pointer by the word size',
				'; which is 4 bytes',
				'push &pointer ; address',
				'push pointer',
				'push %buffer  ; word size',
				'add',
				'store',
				'',
				'; Reset the buffer pointer',
				'; when it reaches the end',
				'; of the buffer',
				'push pointer',
				'push buffer&  ; end address',
				'greaterThan ',
				'if void',
				'push &pointer ; address',
				'push &buffer  ; address',
				'store',
				'ifEnd',
				'',
				'moduleEnd',
			],
			gridCoordinates: {
				x: 124,
				y: -63,
			},
		},
		{
			code: [
				'constants env',
				'; Auto-generated environment constants',
				'; Changes will be overwritten',
				'; Last updated: 1/21/2026, 2:21:06 PM',
				'',
				'const SAMPLE_RATE 44100',
				'const AUDIO_BUFFER_SIZE 128',
				'',
				'; Binary asset sizes in bytes',
				"; 'amen_170bpm_8bit_unsigned.pcm'",
				'const ASSET_0_SIZE 62258',
				'',
				'constantsEnd',
			],
			gridCoordinates: {
				x: 32,
				y: -63,
			},
		},
		{
			code: [
				'module pcmPlayer8bit',
				'use env',
				'',
				'int8u[] buffer ASSET_0_SIZE',
				'int playhead &buffer',
				'float out',
				'int startPos 0',
				'int endPos ASSET_0_SIZE',
				'',
				'# scan buffer playhead',
				'',
				'; Read sample at playhead',
				'; write it to output',
				'push &out',
				'push playhead',
				'load8u',
				'castToFloat',
				'push ^buffer ; max value',
				'castToFloat',
				'div',
				'push 0.5',
				'sub',
				'store',
				'',
				'; Advance the playhead',
				'push &playhead',
				'push playhead',
				'push %buffer ; word size',
				'add',
				'store',
				'',
				'; Reset playhead',
				'; when reaches buffer end',
				'push playhead',
				'push &buffer',
				'push endPos',
				'add',
				'greaterThan',
				'if void',
				'push &playhead',
				'push &buffer',
				'push startPos',
				'add',
				'store',
				'ifEnd',
				'',
				'moduleEnd',
			],
			gridCoordinates: {
				x: 85,
				y: -63,
			},
		},
	],
	viewport: {
		gridCoordinates: {
			x: -10,
			y: -64,
		},
	},
};

export default project;
