import type { Project } from '@8f4e/editor-state';

const project: Project = {
	codeBlocks: [
		{
			code: [
				'config project',
				'; @pos -141 4',
				'',
				'scope "memorySizeBytes"',
				'push 65536',
				'set',
				'popScope',
				'',
				'configEnd',
			],
		},
		{
			code: [
				'config project',
				'; @pos -141 19',
				'',
				'scope "runtimeSettings"',
				'',
				'scope "sampleRate"',
				'push 44100',
				'set',
				'',
				'rescopeTop "runtime"',
				'push "AudioWorkletRuntime"',
				'set',
				'',
				'configEnd',
			],
		},
		{
			code: [
				'config project',
				'; @pos -106 13',
				'',
				'rescope "runtimeSettings"',
				'scope "audioOutputBuffers[0]"',
				'',
				'scope "memoryId"',
				'push "audiooutL.buffer"',
				'set',
				'',
				'rescopeTop "channel"',
				'push 0',
				'set',
				'',
				'rescopeTop "output"',
				'push 0',
				'set',
				'',
				'rescope "runtimeSettings"',
				'scope "audioOutputBuffers[1]"',
				'',
				'scope "memoryId"',
				'push "audiooutR.buffer"',
				'set',
				'',
				'rescopeTop "channel"',
				'push 1',
				'set',
				'',
				'rescopeTop "output"',
				'push 0',
				'set',
				'',
				'configEnd',
			],
		},
		{
			code: [
				'config project',
				'; @pos -106 -10',
				'',
				'rescope "runtimeSettings"',
				'scope "audioInputBuffers[0]"',
				'',
				'scope "memoryId"',
				'push "audioin.buffer"',
				'set',
				'',
				'rescopeTop "channel"',
				'push 0',
				'set',
				'',
				'rescopeTop "input"',
				'push 0',
				'set',
				'',
				'configEnd',
			],
		},
		{
			code: [
				'module audioin',
				'; @pos 5 1',
				'use env',
				'',
				'; Audio buffer',
				'float[] buffer AUDIO_BUFFER_SIZE',
				'float out',
				'int pointer &buffer',
				'',
				'; @plot buffer -2 2',
				'',
				'push &out',
				'push pointer',
				'loadFloat',
				'store',
				'',
				'push &pointer ',
				'push pointer',
				'push %buffer',
				'add',
				'store',
				'',
				'push pointer',
				'push buffer&',
				'greaterThan',
				'if void',
				' push &pointer',
				' push &buffer',
				' store',
				'ifEnd',
				'',
				'moduleEnd',
			],
		},
		{
			code: [
				'module audiooutL',
				'; @pos 48 1',
				'use env',
				'',
				'float* in &audioin.out',
				'',
				'; Audio buffer',
				'float[] buffer AUDIO_BUFFER_SIZE',
				'int pointer &buffer',
				'',
				'; @plot buffer -2 2',
				'',
				'; Store the input value',
				'; in the buffer',
				'push pointer',
				'push *in',
				'store',
				'',
				'; Increment the buffer ',
				'; pointer by the',
				'; buffer word size',
				'push &pointer',
				'push pointer',
				'push %buffer',
				'add',
				'store',
				'',
				'; Reset the buffer pointer',
				'; when it reaches the end',
				'; of the buffer',
				'push pointer',
				'push buffer&',
				'greaterThan',
				'if void',
				' push &pointer',
				' push &buffer',
				' store',
				'ifEnd',
				'',
				'moduleEnd',
			],
		},
		{
			code: [
				'module audiooutR',
				'; @pos 89 1',
				'use env',
				'',
				'float* in &audioin.out',
				'',
				'; Audio buffer',
				'float[] buffer AUDIO_BUFFER_SIZE',
				'int pointer &buffer',
				'',
				'; @plot buffer -2 2',
				'',
				'; Store the input value',
				'; in the buffer',
				'push pointer',
				'push *in',
				'store',
				'',
				'; Increment the buffer ',
				'; pointer by the',
				'; buffer word size',
				'push &pointer',
				'push pointer',
				'push %buffer',
				'add',
				'store',
				'',
				'; Reset the buffer pointer',
				'; when it reaches the end',
				'; of the buffer',
				'push pointer',
				'push buffer&',
				'greaterThan',
				'if void',
				' push &pointer',
				' push &buffer',
				' store',
				'ifEnd',
				'',
				'moduleEnd',
			],
		},
		{
			code: [
				'constants env',
				'; @pos -52 1',
				'; Auto-generated environment constants',
				'; Changes will be overwritten',
				'; Last updated: 1/19/2026, 9:50:35 PM',
				'',
				'const SAMPLE_RATE 44100',
				'const AUDIO_BUFFER_SIZE 128',
				'',
				'constantsEnd',
			],
		},
	],
};

export default project;
