import type { Project } from '@8f4e/editor-state';

const project: Project = {
	codeBlocks: [
		{
			code: [
				'config project',
				'; @pos -67 16',
				'',
				'rescope "memorySizeBytes"',
				'push 65536',
				'set',
				'',

				'rescope "runtimeSettings"',
				'',
				'scope "sampleRate"',
				'push 50',
				'set',
				'',
				'rescopeTop "runtime"',
				'push "WebWorkerLogicRuntime"',
				'set',
				'',
				'configEnd',
			],
		},
		{
			code: [
				'module andGate',
				'; @pos 243 31',
				'',
				'         ;   .---.',
				"int* in1 ; --+    '   ",
				'int out  ;   | AND |---',
				'int* in2 ; --+    .',
				"         ;   '---'",
				'',
				'init in1 &orGate.out',
				'init in2 &negate.out',
				'push &out',
				'push *in1',
				'push *in2',
				'mul',
				'push 1',
				'greaterOrEqual',
				'if ',
				'push 1',
				'else',
				'push 0',
				'ifEnd',
				'store',
				'',
				'moduleEnd',
			],
		},
		{
			code: [
				'module buttons',
				'; @pos 196 16',
				'',
				'; Buttons for the SR AND-OR latch',
				'',
				'int set',
				'int reset',
				'               ; Push this button',
				'               ; to set the state',
				'; @button set 0 1 ; of the latch  -->  ',
				'',
				'                 ; Push this button',
				'; @button reset 0 1 ; to reset   --->',
				'',
				'moduleEnd',
			],
		},
		{
			code: [
				'module comment',
				'; @pos 131 14',
				'',
				'; Of course there is an easier',
				'; way to implement latching',
				'; logic in 8F4E, this is just',
				'; a fun project to demonstrate',
				'; feedback between modules.',
				'',
				'',
				'moduleEnd',
			],
		},
		{
			code: [
				'constants env',
				'; @pos -30 16',
				'; Auto-generated environment constants',
				'; Changes will be overwritten',
				'; Last updated: 1/19/2026, 9:52:44 PM',
				'',
				'const SAMPLE_RATE 50',
				'const AUDIO_BUFFER_SIZE 128',
				'',
				'constantsEnd',
			],
		},
		{
			code: [
				'module negate',
				'; @pos 207 33',
				'',
				'int* in &buttons.reset',
				'int out',
				'',
				'push &out',
				'push *in',
				'push 0',
				'equal',
				'if ',
				'push 1',
				'else',
				'push 0',
				'ifEnd',
				'store',
				'',
				'moduleEnd',
			],
		},
		{
			code: [
				'module norGate',
				'; @pos 95 35',
				'',
				'         ;   .---.',
				"int* in1 ; --+    '",
				'int out  ;   ) NOR |O--- ',
				'int* in2 ; --+    .',
				"         ;   '---'",
				'; @debug out',
				'',
				'init in1 &norGate2.out',
				'init in2 &resetButton.out',
				'',
				'push &out',
				'push *in1',
				'push *in2',
				'add',
				'push 0',
				'equal',
				'if ',
				'push 1',
				'else',
				'push 0',
				'ifEnd',
				'store',
				'',
				'moduleEnd',
			],
		},
		{
			code: [
				'module norGate2',
				'; @pos 95 8',
				'',
				'         ;   .---.',
				"int* in1 ; --+    '   ",
				'int out  ;   ) NOR |O--- ',
				'int* in2 ; --+    .',
				"         ;   '---'",
				'',
				'; @debug out',
				'',
				'init in1 &norGate.out',
				'init in2 &setButton.out',
				'push &out',
				'push *in1',
				'push *in2',
				'add',
				'push 0',
				'equal',
				'if ',
				'push 1 ',
				'else',
				'push 0',
				'ifEnd',
				'store',
				'',
				'moduleEnd',
			],
		},
		{
			code: [
				'module orGate',
				'; @pos 243 6',
				'',
				'         ;   .---.',
				"int* in1 ; --+    '   ",
				'int out  ;   ) OR  |---',
				'int* in2 ; --+    .',
				"         ;   '---'",
				'',
				'init in1 &andGate.out',
				'init in2 &buttons.set',
				'push &out',
				'push *in1',
				'push *in2',
				'add',
				'push 1',
				'greaterOrEqual',
				'if ',
				'push 1',
				'else',
				'push 0',
				'ifEnd',
				'store',
				'',
				'moduleEnd',
			],
		},
		{
			code: [
				'module resetButton',
				'; @pos 47 27',
				'',
				'int out',
				'               ; Push this button',
				'               ; to reset the state',
				'; @button out 0 1 ; of the SR latch -->  ',
				'',
				'moduleEnd',
			],
		},
		{
			code: [
				'module scope',
				'; @pos 131 26',
				'',
				'int* in &norGate.out',
				'int[] buffer 64',
				'int bufferPointer &buffer',
				'',
				'; @plot buffer -1 2',
				'',
				'push &bufferPointer',
				'push bufferPointer',
				'push %buffer',
				'add',
				'store',
				'',
				'push bufferPointer',
				'push buffer&',
				'greaterThan',
				'if void',
				' push &bufferPointer',
				' push &buffer',
				' store',
				'ifEnd',
				'',
				'push bufferPointer',
				'push *in',
				'store',
				'',
				'moduleEnd',
			],
		},
		{
			code: [
				'module scope2',
				'; @pos 279 19',
				'',
				'int* in &andGate.out',
				'int[] buffer 64',
				'int bufferPointer &buffer',
				'',
				'; @plot buffer -1 2',
				'',
				'push &bufferPointer',
				'push bufferPointer',
				'push %buffer',
				'add',
				'store',
				'',
				'push bufferPointer',
				'push buffer&',
				'greaterThan',
				'if void',
				'push &bufferPointer',
				'push &buffer',
				'store',
				'ifEnd',
				'',
				'push bufferPointer',
				'push *in',
				'store',
				'',
				'moduleEnd',
			],
		},
		{
			code: [
				'module setButton',
				'; @pos 47 17',
				'',
				'int out',
				'               ; Push this button',
				'               ; to set the state',
				'; @button out 0 1 ; of the SR latch -->  ',
				'',
				'moduleEnd',
			],
		},
	],
};

export default project;
