import type { Project } from '@8f4e/editor-state';

const project: Project = {
	codeBlocks: [
		{
			code: [
				'config project',
				'; @pos -9 -73',
				'',
				'scope "memorySizeBytes"',
				'push 128',
				'set',
				'',

				'rescope "runtimeSettings"',
				'',
				'scope "sampleRate"',
				'push 10',
				'set',
				'',
				'rescopeTop "runtime"',
				'push "WebWorkerLogicRuntime"',
				'set',
				'',
				'configEnd',
			],
		},
		{
			code: [
				'module activationFn',
				'; @pos 152 -82',
				'',
				'float* in &perceptron.out',
				'float out',
				'',
				'push &out',
				'push *in',
				'call sigmoid',
				'store',
				'',
				'moduleEnd',
			],
		},
		{
			code: [
				'module activationFn2',
				'; @pos 152 -55',
				'',
				'float* in &perceptron2.out',
				'float out',
				'',
				'push &out',
				'push *in',
				'call sigmoid',
				'store',
				'',
				'moduleEnd',
			],
		},
		{
			code: [
				'module activationFn3',
				'; @pos 231 -65',
				'',
				'float* in &perceptron3.out',
				'int out',
				'',
				'push &out',
				'',
				'push *in',
				'call sigmoid',
				'',
				'push 0.5',
				'greaterThan',
				'if int',
				'push 1',
				'else',
				'push 0',
				'ifEnd',
				'',
				'store',
				'',
				'moduleEnd',
			],
		},
		{
			code: [
				'constants env',
				'; @pos -9 -50',
				'; Auto-generated environment constants',
				'; Changes will be overwritten',
				'; Last updated: 1/19/2026, 9:57:55 PM',
				'',
				'const SAMPLE_RATE 10',
				'const AUDIO_BUFFER_SIZE 128',
				'',
				'constantsEnd',
			],
		},
		{
			code: [
				'module perceptron',
				'; @pos 118 -82',
				'; Pre-trained perceptron',
				'',
				'float* in1 &switches.out1',
				'float* in2 &switches.out2',
				'float out',
				'',
				'; Weights',
				'const W1 10.056234',
				'const W2 -42.53689',
				'const BIAS -3.92453',
				'',
				'push &out',
				'push *in1',
				'push W1',
				'mul',
				'push *in2',
				'push W2',
				'mul',
				'add',
				'push BIAS',
				'add',
				'store',
				'moduleEnd',
			],
		},
		{
			code: [
				'module perceptron2',
				'; @pos 118 -55',
				'; Pre-trained perceptron',
				'',
				'float* in1 &switches.out1',
				'float* in2 &switches.out2',
				'float out',
				'',
				'; Weights',
				'const W1 -70.313797',
				'const W2 24.76387',
				'const BIAS -8.765101',
				'',
				'push &out',
				'push *in1',
				'push W1',
				'mul',
				'push *in2',
				'push W2',
				'mul',
				'add',
				'push BIAS',
				'add',
				'store',
				'moduleEnd',
			],
		},
		{
			code: [
				'module perceptron3',
				'; @pos 193 -65',
				'; Pre-trained perceptron',
				'',
				'float* in1 &activationFn.out',
				'float* in2 &activationFn2.out',
				'float out ',
				'',
				'; Weights',
				'const W1 6.94625',
				'const W2 6.64608',
				'const BIAS 6.05782',
				'',
				'push &out',
				'push *in1',
				'push W1',
				'mul',
				'push *in2',
				'push W2',
				'mul',
				'add',
				'push BIAS',
				'add',
				'store',
				'moduleEnd',
			],
		},
		{
			code: ['module result', '; @pos 74 -53', '', 'int* in &activationFn3.out', '', '; @debug *in', '', 'moduleEnd'],
		},
		{
			code: [
				'function sigmoid',
				'; @pos 73 -82',
				'param float x',
				'; Polynomial sigmoid',
				'; func. approximation',
				'',
				'localGet x',
				'dup',
				'abs',
				'push 1.0',
				'add',
				'ensureNonZero',
				'div',
				'',
				'functionEnd float',
			],
		},
		{
			code: ['module switches', '; @pos 74 -62', '', 'int he', 'float out1 1.0', 'float out2 0.0', '', 'moduleEnd'],
		},
	],
	viewport: {
		gridCoordinates: {
			x: 70,
			y: -84,
		},
	},
};

export default project;
