import { defineConfig } from 'vitest/config';
import { createNodePreset } from '@8f4e/config/vitest';

export default defineConfig(
	createNodePreset({
		include: [
			'tests/**/*.test.ts',
			'src/wasmUtils/ieee754.ts',
			'src/wasmUtils/unsignedLEB128.ts',
			'src/wasmUtils/signedLEB128.ts',
			'src/wasmUtils/encodeString.ts',
			'src/wasmUtils/createVector.ts',
			'src/wasmUtils/localGet.ts',
			'src/wasmUtils/localSet.ts',
			'src/wasmUtils/call.ts',
			'src/wasmUtils/i32const.ts',
			'src/wasmUtils/f32const.ts',
			'src/wasmUtils/i32store.ts',
			'src/wasmUtils/f32store.ts',
			'src/wasmUtils/load/i32load.ts',
			'src/wasmUtils/load/i32load8s.ts',
			'src/wasmUtils/load/i32load8u.ts',
			'src/wasmUtils/load/i32load16s.ts',
			'src/wasmUtils/load/i32load16u.ts',
			'src/wasmUtils/load/f32load.ts',
			'src/wasmUtils/controlFlow/ifelse.ts',
			'src/wasmUtils/controlFlow/br.ts',
			'src/wasmUtils/controlFlow/br_if.ts',
			'src/wasmUtils/controlFlow/loop.ts',
			'src/wasmUtils/controlFlow/block.ts',
			'src/wasmUtils/typeFunction/createFunctionType.ts',
			'src/wasmUtils/typeFunction/createTypeSection.ts',
			'src/wasmUtils/typeFunction/createFunctionSection.ts',
			'src/wasmUtils/export/createFunctionExport.ts',
			'src/wasmUtils/export/createExportSection.ts',
			'src/wasmUtils/codeSection/createLocalDeclaration.ts',
			'src/wasmUtils/codeSection/createFunction.ts',
			'src/wasmUtils/codeSection/createCodeSection.ts',
			'src/wasmUtils/memorySection.ts',
			'src/wasmUtils/import/createMemoryImport.ts',
			'src/wasmUtils/import/createImportSection.ts',
			'src/wasmUtils/nameSection.ts',
		],
		additionalExclude: ['**/testUtils.ts', '**/__fixtures__/**'],
		typecheckEnabled: true,
	})
);
