// Re-export all types from the shared editor-state-types package
export type {
	State,
	CodeBlockGraphicData,
	Project,
	Options,
	EditorSettings,
	CompilationResult,
	CodeBlock,
	Viewport,
	Size,
	Position,
	ContextMenuItem,
	MenuGenerator,
	BuildError,
	Compiler,
	Midi,
	GraphicHelper,
	BinaryAsset,
	Callbacks,
	ExampleModule,
	ModuleMetadata,
	ProjectMetadata,
	Runtimes,
	WebWorkerLogicRuntime,
	MainThreadLogicRuntime,
	AudioWorkletRuntime,
	WebWorkerMIDIRuntime,
	MemoryIdentifier,
	BufferPlotter,
	Switch,
	Debugger,
	Output,
	Input,
	PianoKeyboard,
	ContextMenu,
	RuntimeFactory,
	RuntimeType,
	FeatureFlags,
	FeatureFlagsConfig,
	EventDispatcher,
	InternalMouseEvent,
	InternalKeyboardEvent,
} from '@8f4e/editor-state-types';

// Re-export EMPTY_DEFAULT_PROJECT as a value
export { EMPTY_DEFAULT_PROJECT } from '@8f4e/editor-state-types';
