import type { ExampleModule, ModuleMetadata } from '@8f4e/editor-state';

/**
 * Manifest of available modules with their lazy loaders.
 * Maps slug -> loader function.
 */
export const moduleManifest: Record<string, () => Promise<ExampleModule>> = {
	XORShift: () => import('@8f4e/examples/modules/XORShift').then(m => m.default),
	amenBreak64Step: () => import('@8f4e/examples/modules/amenBreak64Step').then(m => m.default),
	arEnvelope: () => import('@8f4e/examples/modules/arEnvelope').then(m => m.default),
	asEnvelope: () => import('@8f4e/examples/modules/asEnvelope').then(m => m.default),
	audioBufferOut: () => import('@8f4e/examples/modules/audioBufferOut').then(m => m.default),
	binSwitchesLSb: () => import('@8f4e/examples/modules/binSwitchesLSb').then(m => m.default),
	binSwitchesMSb: () => import('@8f4e/examples/modules/binSwitchesMSb').then(m => m.default),
	binaryGateSequencer: () => import('@8f4e/examples/modules/binaryGateSequencer').then(m => m.default),
	binaryShiftRegister: () => import('@8f4e/examples/modules/binaryShiftRegister').then(m => m.default),
	bitcrusher: () => import('@8f4e/examples/modules/bitcrusher').then(m => m.default),
	bitwiseAnd: () => import('@8f4e/examples/modules/bitwiseAnd').then(m => m.default),
	bitwiseOr: () => import('@8f4e/examples/modules/bitwiseOr').then(m => m.default),
	bitwiseXor: () => import('@8f4e/examples/modules/bitwiseXor').then(m => m.default),
	bpmClock: () => import('@8f4e/examples/modules/bpmClock').then(m => m.default),
	break16Step1: () => import('@8f4e/examples/modules/break16Step1').then(m => m.default),
	break16Step2: () => import('@8f4e/examples/modules/break16Step2').then(m => m.default),
	bufferCombinerInt: () => import('@8f4e/examples/modules/bufferCombinerInt').then(m => m.default),
	bufferCombinerIntFloat: () => import('@8f4e/examples/modules/bufferCombinerIntFloat').then(m => m.default),
	bufferCopierFloat: () => import('@8f4e/examples/modules/bufferCopierFloat').then(m => m.default),
	bufferCopierInt: () => import('@8f4e/examples/modules/bufferCopierInt').then(m => m.default),
	bufferFloatToInt: () => import('@8f4e/examples/modules/bufferFloatToInt').then(m => m.default),
	bufferIntToFloat: () => import('@8f4e/examples/modules/bufferIntToFloat').then(m => m.default),
	bufferReplicatorWithOffsetInt: () =>
		import('@8f4e/examples/modules/bufferReplicatorWithOffsetInt').then(m => m.default),
	bufferReplicatorWithOffsetIntFloat: () =>
		import('@8f4e/examples/modules/bufferReplicatorWithOffsetIntFloat').then(m => m.default),
	bufferReverserFloat: () => import('@8f4e/examples/modules/bufferReverserFloat').then(m => m.default),
	bufferReverserInt: () => import('@8f4e/examples/modules/bufferReverserInt').then(m => m.default),
	changeDetectorInt: () => import('@8f4e/examples/modules/changeDetectorInt').then(m => m.default),
	clockDivider: () => import('@8f4e/examples/modules/clockDivider').then(m => m.default),
	decToBin8bitMSb: () => import('@8f4e/examples/modules/decToBin8bitMSb').then(m => m.default),
	delay: () => import('@8f4e/examples/modules/delay').then(m => m.default),
	expLookupTable: () => import('@8f4e/examples/modules/expLookupTable').then(m => m.default),
	generalMIDIDrumCodes: () => import('@8f4e/examples/modules/generalMIDIDrumCodes').then(m => m.default),
	highPassFilter: () => import('@8f4e/examples/modules/highPassFilter').then(m => m.default),
	integerLimits: () => import('@8f4e/examples/modules/integerLimits').then(m => m.default),
	linearCongruentialGenerator: () => import('@8f4e/examples/modules/linearCongruentialGenerator').then(m => m.default),
	lowPassFilter: () => import('@8f4e/examples/modules/lowPassFilter').then(m => m.default),
	mapToRangeFloat: () => import('@8f4e/examples/modules/mapToRangeFloat').then(m => m.default),
	mapToRangeFloatToInt: () => import('@8f4e/examples/modules/mapToRangeFloatToInt').then(m => m.default),
	mapToRangeInt: () => import('@8f4e/examples/modules/mapToRangeInt').then(m => m.default),
	mapToVariableRangeFloat: () => import('@8f4e/examples/modules/mapToVariableRangeFloat').then(m => m.default),
	masterClock: () => import('@8f4e/examples/modules/masterClock').then(m => m.default),
	math: () => import('@8f4e/examples/modules/math').then(m => m.default),
	midiCCOut: () => import('@8f4e/examples/modules/midiCCOut').then(m => m.default),
	midiCodes: () => import('@8f4e/examples/modules/midiCodes').then(m => m.default),
	midiFrequenciesLookupTable: () => import('@8f4e/examples/modules/midiFrequenciesLookupTable').then(m => m.default),
	midiNoteOut: () => import('@8f4e/examples/modules/midiNoteOut').then(m => m.default),
	midiPianoKeyboardC3: () => import('@8f4e/examples/modules/midiPianoKeyboardC3').then(m => m.default),
	morse: () => import('@8f4e/examples/modules/morse').then(m => m.default),
	morseHex: () => import('@8f4e/examples/modules/morseHex').then(m => m.default),
	multipleFloat: () => import('@8f4e/examples/modules/multipleFloat').then(m => m.default),
	multipleInt: () => import('@8f4e/examples/modules/multipleInt').then(m => m.default),
	pcmLooper8bitUnsigned: () => import('@8f4e/examples/modules/pcmLooper8bitUnsigned').then(m => m.default),
	pcmLooper8bitUnsignedWithReset: () =>
		import('@8f4e/examples/modules/pcmLooper8bitUnsignedWithReset').then(m => m.default),
	pcmLooperV16bitSigned: () => import('@8f4e/examples/modules/pcmLooperV16bitSigned').then(m => m.default),
	pcmLooperVR16bitSigned: () => import('@8f4e/examples/modules/pcmLooperVR16bitSigned').then(m => m.default),
	pcmLooperVRP16bitSigned: () => import('@8f4e/examples/modules/pcmLooperVRP16bitSigned').then(m => m.default),
	peakHolderNegativeFloat: () => import('@8f4e/examples/modules/peakHolderNegativeFloat').then(m => m.default),
	peakHolderPositiveFloat: () => import('@8f4e/examples/modules/peakHolderPositiveFloat').then(m => m.default),
	phaseAccumulator: () => import('@8f4e/examples/modules/phaseAccumulator').then(m => m.default),
	quantizer: () => import('@8f4e/examples/modules/quantizer').then(m => m.default),
	reverb: () => import('@8f4e/examples/modules/reverb').then(m => m.default),
	ringModulator: () => import('@8f4e/examples/modules/ringModulator').then(m => m.default),
	sampleAndHoldFloat: () => import('@8f4e/examples/modules/sampleAndHoldFloat').then(m => m.default),
	sampleAndHoldInt: () => import('@8f4e/examples/modules/sampleAndHoldInt').then(m => m.default),
	sawSignedFloat: () => import('@8f4e/examples/modules/sawSignedFloat').then(m => m.default),
	sawUnsigned8bitInt: () => import('@8f4e/examples/modules/sawUnsigned8bitInt').then(m => m.default),
	scopeSignedFloat: () => import('@8f4e/examples/modules/scopeSignedFloat').then(m => m.default),
	scopeUnsignedInt: () => import('@8f4e/examples/modules/scopeUnsignedInt').then(m => m.default),
	sequencerFloat: () => import('@8f4e/examples/modules/sequencerFloat').then(m => m.default),
	sequencerInt: () => import('@8f4e/examples/modules/sequencerInt').then(m => m.default),
	sequentialDemuxFloat: () => import('@8f4e/examples/modules/sequentialDemuxFloat').then(m => m.default),
	sequentialDemuxInt: () => import('@8f4e/examples/modules/sequentialDemuxInt').then(m => m.default),
	sequentialMuxFloat: () => import('@8f4e/examples/modules/sequentialMuxFloat').then(m => m.default),
	sequentialMuxInt: () => import('@8f4e/examples/modules/sequentialMuxInt').then(m => m.default),
	shiftRegisterFloat: () => import('@8f4e/examples/modules/shiftRegisterFloat').then(m => m.default),
	shiftRegisterInt: () => import('@8f4e/examples/modules/shiftRegisterInt').then(m => m.default),
	sigmoid: () => import('@8f4e/examples/modules/sigmoid').then(m => m.default),
	sigmoidPolynomialApproximation: () =>
		import('@8f4e/examples/modules/sigmoidPolynomialApproximation').then(m => m.default),
	sine: () => import('@8f4e/examples/modules/sine').then(m => m.default),
	sineLookupTable: () => import('@8f4e/examples/modules/sineLookupTable').then(m => m.default),
	squareSignedFloat: () => import('@8f4e/examples/modules/squareSignedFloat').then(m => m.default),
	strumFloat: () => import('@8f4e/examples/modules/strumFloat').then(m => m.default),
	switchGatesFloat: () => import('@8f4e/examples/modules/switchGatesFloat').then(m => m.default),
	switchGatesInt: () => import('@8f4e/examples/modules/switchGatesInt').then(m => m.default),
	triangleSignedFloat: () => import('@8f4e/examples/modules/triangleSignedFloat').then(m => m.default),
};

/**
 * Hardcoded metadata for all modules.
 * This allows listing modules without loading their heavy code payloads.
 * Metadata is kept in sync with actual module files.
 */
export const moduleMetadata: ModuleMetadata[] = [
	{ slug: 'XORShift', title: 'XORShift (Signed, Float, -1 - 1)', category: 'Random' },
	{ slug: 'amenBreak64Step', title: 'Amen Break 64 Step', category: 'Break Beats' },
	{ slug: 'arEnvelope', title: 'Attack-Release Envelope', category: 'Envelopes' },
	{ slug: 'asEnvelope', title: 'Attack-Sustain Envelope', category: 'Envelopes' },
	{ slug: 'audioBufferOut', title: 'Audio Buffer Out', category: 'Audio Buffer' },
	{ slug: 'binSwitchesLSb', title: 'Binary Switches (LSb first)', category: 'Controllers' },
	{ slug: 'binSwitchesMSb', title: 'Binary Switches (MSb first)', category: 'Controllers' },
	{ slug: 'binaryGateSequencer', title: 'Binary Gate Sequencer', category: 'Sequencers' },
	{ slug: 'binaryShiftRegister', title: 'Binary Shift Register', category: 'Bitwise' },
	{ slug: 'bitcrusher', title: 'Bitcrusher', category: 'Effects' },
	{ slug: 'bitwiseAnd', title: 'Bitwise AND', category: 'Bitwise' },
	{ slug: 'bitwiseOr', title: 'Bitwise OR', category: 'Bitwise' },
	{ slug: 'bitwiseXor', title: 'Bitwise XOR', category: 'Bitwise' },
	{ slug: 'bpmClock', title: 'BPM Clock', category: 'Clock' },
	{ slug: 'break16Step1', title: '16 Step Break 1', category: 'Break Beats' },
	{ slug: 'break16Step2', title: '16 Step Break 2', category: 'Break Beats' },
	{ slug: 'bufferCombinerInt', title: 'Buffer Combiner (Int)', category: 'Buffer' },
	{ slug: 'bufferCombinerIntFloat', title: 'Buffer Combiner (Float)', category: 'Buffer' },
	{ slug: 'bufferCopierFloat', title: 'Buffer Copier (Float)', category: 'Buffer' },
	{ slug: 'bufferCopierInt', title: 'Buffer Copier (Int)', category: 'Buffer' },
	{ slug: 'bufferFloatToInt', title: 'Float Buffer to Int Buffer Converter', category: 'Buffer' },
	{ slug: 'bufferIntToFloat', title: 'Int Buffer to Float Buffer Converter', category: 'Buffer' },
	{
		slug: 'bufferReplicatorWithOffsetInt',
		title: 'Buffer Replicator with Offset (Int)',
		category: 'Buffer',
	},
	{
		slug: 'bufferReplicatorWithOffsetIntFloat',
		title: 'Buffer Replicator with Offset (Int)',
		category: 'Buffer',
	},
	{ slug: 'bufferReverserFloat', title: 'Buffer Reverser (Float)', category: 'Buffer' },
	{ slug: 'bufferReverserInt', title: 'Buffer Reverser (Int)', category: 'Buffer' },
	{ slug: 'changeDetectorInt', title: 'Change Detector (Int)', category: 'Trigger' },
	{ slug: 'clockDivider', title: 'Clock Divider', category: 'Clock' },
	{ slug: 'decToBin8bitMSb', title: 'Decimal to Binary Converter (8bit, MSb)', category: 'Bitwise' },
	{ slug: 'delay', title: 'Delay', category: 'Effects' },
	{ slug: 'expLookupTable', title: 'Exponent Function Lookup Table (-1...1)', category: 'Lookup Tables' },
	{ slug: 'generalMIDIDrumCodes', title: 'General MIDI Drum Codes', category: 'Constants' },
	{ slug: 'highPassFilter', title: 'High-pass Filter', category: 'Filters' },
	{ slug: 'integerLimits', title: 'Integer Limits', category: 'Constants' },
	{
		slug: 'linearCongruentialGenerator',
		title: 'Linear Congruential Generator (Signed, Float, 16bit, -1 - 1)',
		category: 'Random',
	},
	{ slug: 'lowPassFilter', title: 'Low-pass Filter', category: 'Filters' },
	{ slug: 'mapToRangeFloat', title: 'Map Signal to Range (Float)', category: 'Utils' },
	{ slug: 'mapToRangeFloatToInt', title: 'Map Signal to Range (Float to Int)', category: 'Utils' },
	{ slug: 'mapToRangeInt', title: 'Map Signal to Range (Int)', category: 'Utils' },
	{ slug: 'mapToVariableRangeFloat', title: 'Map Signal to Variable Range (Float)', category: 'Utils' },
	{ slug: 'masterClock', title: 'Master Clock', category: 'Clock' },
	{ slug: 'math', title: 'Math Constants', category: 'Constants' },
	{ slug: 'midiCCOut', title: 'MIDI CC Out', category: 'MIDI' },
	{ slug: 'midiCodes', title: 'MIDI Codes', category: 'Constants' },
	{ slug: 'midiFrequenciesLookupTable', title: 'MIDI Frequencies Lookup Table', category: 'Lookup Tables' },
	{ slug: 'midiNoteOut', title: 'MIDI Note Out', category: 'MIDI' },
	{ slug: 'midiPianoKeyboardC3', title: 'MIDI Piano Keyboard (First key: C3)', category: 'MIDI' },
	{ slug: 'morse', title: 'Morse Code', category: 'Constants' },
	{ slug: 'morseHex', title: 'Morse Code (Hex)', category: 'Constants' },
	{ slug: 'multipleFloat', title: 'Multiple (8x Float)', category: 'Utilities' },
	{ slug: 'multipleInt', title: 'Multiple (8x Int)', category: 'Utilities' },
	{ slug: 'pcmLooper8bitUnsigned', title: 'PCM Looper (8bit unsigned)', category: 'PCM' },
	{ slug: 'pcmLooper8bitUnsignedWithReset', title: 'PCM Looper with Reset (8bit unsigned)', category: 'PCM' },
	{ slug: 'pcmLooperV16bitSigned', title: 'Variable Speed PCM Looper (16bit signed)', category: 'PCM' },
	{
		slug: 'pcmLooperVR16bitSigned',
		title: 'Variable Speed and Retriggerable PCM Looper (16bit signed)',
		category: 'PCM',
	},
	{
		slug: 'pcmLooperVRP16bitSigned',
		title: 'Retriggerable PCM Looper with Variable Speed and Start Position (16bit signed)',
		category: 'PCM',
	},
	{ slug: 'peakHolderNegativeFloat', title: 'Peak Holder (Negative, Float)', category: 'Debug Tools' },
	{ slug: 'peakHolderPositiveFloat', title: 'Peak Holder (Positive, Float)', category: 'Debug Tools' },
	{
		slug: 'phaseAccumulator',
		title: 'Phase Accumulator (Periodic, Float)',
		description: 'Phase accumulator that can drive any periodic function (defaults to sine).',
		category: 'Oscillators',
	},
	{ slug: 'quantizer', title: 'Quantizer', category: 'Quantizers' },
	{ slug: 'reverb', title: 'Reverb', category: 'Effects' },
	{ slug: 'ringModulator', title: 'Ring Modulator', category: 'Modulation' },
	{ slug: 'sampleAndHoldFloat', title: 'Sample & Hold (Float)', category: 'Utils' },
	{ slug: 'sampleAndHoldInt', title: 'Sample & Hold (Int)', category: 'Utils' },
	{ slug: 'sawSignedFloat', title: 'Saw (Signed, Float)', category: 'Oscillators' },
	{ slug: 'sawUnsigned8bitInt', title: 'Saw (Unsigned, Int, 8bit)', category: 'Oscillators' },
	{ slug: 'scopeSignedFloat', title: 'Scope (Signed, Float, -1-1)', category: 'Debug Tools' },
	{ slug: 'scopeUnsignedInt', title: 'Scope (Unsigned, Int, 0-255)', category: 'Debug Tools' },
	{ slug: 'sequencerFloat', title: 'Sequencer (Float)', category: 'Sequencers' },
	{ slug: 'sequencerInt', title: 'Sequencer (Int)', category: 'Sequencers' },
	{ slug: 'sequentialDemuxFloat', title: 'Sequential Demultiplexer (8 output, Float)', category: 'Sequencers' },
	{ slug: 'sequentialDemuxInt', title: 'Sequential Demultiplexer (8 output, Int)', category: 'Sequencers' },
	{ slug: 'sequentialMuxFloat', title: 'Sequential Multiplexer (8 input, Float)', category: 'Sequencers' },
	{ slug: 'sequentialMuxInt', title: 'Sequential Multiplexer (8 input, Int)', category: 'Sequencers' },
	{ slug: 'shiftRegisterFloat', title: 'Shift Register (8 outs, Float)', category: 'Utilities' },
	{ slug: 'shiftRegisterInt', title: 'Shift Register (8 outs, Int)', category: 'Utilities' },
	{ slug: 'sigmoid', title: 'Sigmoid (Polynomial Approximation)', category: 'Functions/Math' },
	{
		slug: 'sigmoidPolynomialApproximation',
		title: 'Sigmoid Function (Polynomial Approximation)',
		category: 'Machine Learning',
	},
	{ slug: 'sine', title: 'Sine [-PI, PI] (Polynomial Approximation)', category: 'Functions/Math' },
	{ slug: 'sineLookupTable', title: 'Sine Lookup Table', category: 'Lookup Tables' },
	{ slug: 'squareSignedFloat', title: 'Square (Signed, Float)', category: 'Oscillators' },
	{ slug: 'strumFloat', title: 'Strum (Float)', category: 'Sequencers' },
	{ slug: 'switchGatesFloat', title: 'Switchable Gates (8x Float)', category: 'Controllers' },
	{ slug: 'switchGatesInt', title: 'Switchable Gates (8x Int)', category: 'Controllers' },
	{ slug: 'triangleSignedFloat', title: 'Triangle (Signed, Float)', category: 'Oscillators' },
];

// For backwards compatibility, export a default object that matches the old API
// but note: accessing properties will not trigger loading - use the registry functions instead
export default moduleManifest;
